<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>Chapter 4 Inferences for Population Means | Statistics and the Physical World</title>
  <meta name="description" content="This is an Introduction to Statistics with applications from the physical world. We will make use of the R programming language for computations." />
  <meta name="generator" content="bookdown 0.43 and GitBook 2.6.7" />

  <meta property="og:title" content="Chapter 4 Inferences for Population Means | Statistics and the Physical World" />
  <meta property="og:type" content="book" />
  
  <meta property="og:description" content="This is an Introduction to Statistics with applications from the physical world. We will make use of the R programming language for computations." />
  <meta name="github-repo" content="rstudio/bookdown-demo" />

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Chapter 4 Inferences for Population Means | Statistics and the Physical World" />
  
  <meta name="twitter:description" content="This is an Introduction to Statistics with applications from the physical world. We will make use of the R programming language for computations." />
  

<meta name="author" content="Larry Winner" />


<meta name="date" content="2026-06-22" />

  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="probability.html"/>
<link rel="next" href="introduction-to-experimentation.html"/>
<script src="libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/fuse.js@6.4.6/dist/fuse.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />








<link href="libs/anchor-sections-1.1.0/anchor-sections.css" rel="stylesheet" />
<link href="libs/anchor-sections-1.1.0/anchor-sections-hash.css" rel="stylesheet" />
<script src="libs/anchor-sections-1.1.0/anchor-sections.js"></script>


<style type="text/css">
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { color: #008000; } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { color: #008000; font-weight: bold; } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

<style type="text/css">
  
  div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
</style>
<style type="text/css">
/* Used with Pandoc 2.11+ new --citeproc when CSL is used */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
  margin-bottom: 0em;
}
.hanging div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}
</style>

<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">STA2170 Notes</a></li>

<li class="divider"></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i>Preface</a></li>
<li class="chapter" data-level="1" data-path="intro.html"><a href="intro.html"><i class="fa fa-check"></i><b>1</b> Introduction</a>
<ul>
<li class="chapter" data-level="1.1" data-path="intro.html"><a href="intro.html#basic-concepts-of-statistical-analysis"><i class="fa fa-check"></i><b>1.1</b> Basic Concepts of Statistical Analysis</a></li>
<li class="chapter" data-level="1.2" data-path="intro.html"><a href="intro.html#data-collection"><i class="fa fa-check"></i><b>1.2</b> Data Collection</a></li>
<li class="chapter" data-level="1.3" data-path="intro.html"><a href="intro.html#variable-types"><i class="fa fa-check"></i><b>1.3</b> Variable Types</a></li>
</ul></li>
<li class="chapter" data-level="2" data-path="describing-data.html"><a href="describing-data.html"><i class="fa fa-check"></i><b>2</b> Describing Data</a>
<ul>
<li class="chapter" data-level="2.1" data-path="describing-data.html"><a href="describing-data.html#graphical-description-of-a-single-variable"><i class="fa fa-check"></i><b>2.1</b> Graphical Description of a Single Variable</a></li>
<li class="chapter" data-level="2.2" data-path="describing-data.html"><a href="describing-data.html#numerical-descriptive-measures-of-a-single-variable"><i class="fa fa-check"></i><b>2.2</b> Numerical Descriptive Measures of a Single Variable</a>
<ul>
<li class="chapter" data-level="2.2.1" data-path="describing-data.html"><a href="describing-data.html#measures-of-central-tendency"><i class="fa fa-check"></i><b>2.2.1</b> Measures of Central Tendency</a></li>
<li class="chapter" data-level="2.2.2" data-path="describing-data.html"><a href="describing-data.html#measures-of-variability"><i class="fa fa-check"></i><b>2.2.2</b> Measures of Variability</a></li>
</ul></li>
<li class="chapter" data-level="2.3" data-path="describing-data.html"><a href="describing-data.html#describing-more-than-one-variable"><i class="fa fa-check"></i><b>2.3</b> Describing More than One Variable</a></li>
</ul></li>
<li class="chapter" data-level="3" data-path="probability.html"><a href="probability.html"><i class="fa fa-check"></i><b>3</b> Probability</a>
<ul>
<li class="chapter" data-level="3.1" data-path="probability.html"><a href="probability.html#terminology-and-probability-rules"><i class="fa fa-check"></i><b>3.1</b> Terminology and Probability Rules</a></li>
<li class="chapter" data-level="3.2" data-path="probability.html"><a href="probability.html#basic-probability"><i class="fa fa-check"></i><b>3.2</b> Basic Probability</a>
<ul>
<li class="chapter" data-level="3.2.1" data-path="probability.html"><a href="probability.html#bayes-rule"><i class="fa fa-check"></i><b>3.2.1</b> Bayes’ Rule</a></li>
</ul></li>
<li class="chapter" data-level="3.3" data-path="probability.html"><a href="probability.html#random-variables-and-probability-distributions"><i class="fa fa-check"></i><b>3.3</b> Random Variables and Probability Distributions</a></li>
<li class="chapter" data-level="3.4" data-path="probability.html"><a href="probability.html#discrete-random-variables"><i class="fa fa-check"></i><b>3.4</b> Discrete Random Variables</a>
<ul>
<li class="chapter" data-level="3.4.1" data-path="probability.html"><a href="probability.html#population-numerical-descriptive-measures"><i class="fa fa-check"></i><b>3.4.1</b> Population Numerical Descriptive Measures</a></li>
<li class="chapter" data-level="3.4.2" data-path="probability.html"><a href="probability.html#common-families-of-discrete-probability-distributions"><i class="fa fa-check"></i><b>3.4.2</b> Common Families of Discrete Probability Distributions</a></li>
</ul></li>
<li class="chapter" data-level="3.5" data-path="probability.html"><a href="probability.html#continuous-random-variables"><i class="fa fa-check"></i><b>3.5</b> Continuous Random Variables</a>
<ul>
<li class="chapter" data-level="3.5.1" data-path="probability.html"><a href="probability.html#common-families-of-continuous-probability-distributions"><i class="fa fa-check"></i><b>3.5.1</b> Common Families of Continuous Probability Distributions</a></li>
</ul></li>
<li class="chapter" data-level="3.6" data-path="probability.html"><a href="probability.html#sampling-distributions-and-the-central-limit-theorem"><i class="fa fa-check"></i><b>3.6</b> Sampling Distributions and the Central Limit Theorem</a></li>
</ul></li>
<li class="chapter" data-level="4" data-path="inferences-for-population-means.html"><a href="inferences-for-population-means.html"><i class="fa fa-check"></i><b>4</b> Inferences for Population Means</a>
<ul>
<li class="chapter" data-level="4.1" data-path="inferences-for-population-means.html"><a href="inferences-for-population-means.html#estimation"><i class="fa fa-check"></i><b>4.1</b> Estimation</a></li>
<li class="chapter" data-level="4.2" data-path="inferences-for-population-means.html"><a href="inferences-for-population-means.html#hypothesis-testing"><i class="fa fa-check"></i><b>4.2</b> Hypothesis Testing</a></li>
</ul></li>
<li class="chapter" data-level="5" data-path="introduction-to-experimentation.html"><a href="introduction-to-experimentation.html"><i class="fa fa-check"></i><b>5</b> Introduction to Experimentation</a></li>
<li class="chapter" data-level="6" data-path="comparing-two-population-means.html"><a href="comparing-two-population-means.html"><i class="fa fa-check"></i><b>6</b> Comparing Two Population Means</a>
<ul>
<li class="chapter" data-level="6.1" data-path="comparing-two-population-means.html"><a href="comparing-two-population-means.html#independent-samples"><i class="fa fa-check"></i><b>6.1</b> Independent Samples</a>
<ul>
<li class="chapter" data-level="6.1.1" data-path="comparing-two-population-means.html"><a href="comparing-two-population-means.html#large-sample-tests"><i class="fa fa-check"></i><b>6.1.1</b> Large-Sample tests</a></li>
<li class="chapter" data-level="6.1.2" data-path="comparing-two-population-means.html"><a href="comparing-two-population-means.html#small-sample-tests-with-normal-data"><i class="fa fa-check"></i><b>6.1.2</b> Small Sample Tests with Normal Data</a></li>
</ul></li>
<li class="chapter" data-level="6.2" data-path="comparing-two-population-means.html"><a href="comparing-two-population-means.html#paired-sample-designs"><i class="fa fa-check"></i><b>6.2</b> Paired Sample Designs</a></li>
<li class="chapter" data-level="6.3" data-path="comparing-two-population-means.html"><a href="comparing-two-population-means.html#nonparametric-tests"><i class="fa fa-check"></i><b>6.3</b> Nonparametric Tests</a>
<ul>
<li class="chapter" data-level="6.3.1" data-path="comparing-two-population-means.html"><a href="comparing-two-population-means.html#independent-samples---wilcoxon-rank-sum-test"><i class="fa fa-check"></i><b>6.3.1</b> Independent Samples - Wilcoxon Rank-Sum Test</a></li>
<li class="chapter" data-level="6.3.2" data-path="comparing-two-population-means.html"><a href="comparing-two-population-means.html#paired-samples---wilcoxon-signed-rank-test"><i class="fa fa-check"></i><b>6.3.2</b> Paired Samples - Wilcoxon Signed Rank Test</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="7" data-path="experimental-design-and-the-analysis-of-variance.html"><a href="experimental-design-and-the-analysis-of-variance.html"><i class="fa fa-check"></i><b>7</b> Experimental Design and the Analysis of Variance</a>
<ul>
<li class="chapter" data-level="7.1" data-path="experimental-design-and-the-analysis-of-variance.html"><a href="experimental-design-and-the-analysis-of-variance.html#completely-randomized-design-crd-for-independent-samples"><i class="fa fa-check"></i><b>7.1</b> Completely Randomized Design (CRD) For Independent Samples</a>
<ul>
<li class="chapter" data-level="7.1.1" data-path="experimental-design-and-the-analysis-of-variance.html"><a href="experimental-design-and-the-analysis-of-variance.html#analysis-of-variance-and-f-test-for-normal-data"><i class="fa fa-check"></i><b>7.1.1</b> Analysis of Variance and <span class="math inline">\(F\)</span>-Test for Normal Data</a></li>
<li class="chapter" data-level="7.1.2" data-path="experimental-design-and-the-analysis-of-variance.html"><a href="experimental-design-and-the-analysis-of-variance.html#comparisons-among-treatment-means"><i class="fa fa-check"></i><b>7.1.2</b> Comparisons among Treatment Means</a></li>
</ul></li>
<li class="chapter" data-level="7.2" data-path="experimental-design-and-the-analysis-of-variance.html"><a href="experimental-design-and-the-analysis-of-variance.html#randomized-block-design-rbd-for-studies-based-on-matched-units"><i class="fa fa-check"></i><b>7.2</b> Randomized Block Design (RBD) For Studies Based on Matched Units</a></li>
<li class="chapter" data-level="7.3" data-path="experimental-design-and-the-analysis-of-variance.html"><a href="experimental-design-and-the-analysis-of-variance.html#factorial-designs"><i class="fa fa-check"></i><b>7.3</b> Factorial Designs</a></li>
</ul></li>
<li class="chapter" data-level="8" data-path="categorical-data-analysis.html"><a href="categorical-data-analysis.html"><i class="fa fa-check"></i><b>8</b> Categorical Data Analysis</a>
<ul>
<li class="chapter" data-level="8.1" data-path="categorical-data-analysis.html"><a href="categorical-data-analysis.html#inference-concerning-a-single-variable"><i class="fa fa-check"></i><b>8.1</b> Inference Concerning a Single Variable</a>
<ul>
<li class="chapter" data-level="8.1.1" data-path="categorical-data-analysis.html"><a href="categorical-data-analysis.html#variables-with-two-possible-outcomes"><i class="fa fa-check"></i><b>8.1.1</b> Variables with Two Possible Outcomes</a></li>
<li class="chapter" data-level="8.1.2" data-path="categorical-data-analysis.html"><a href="categorical-data-analysis.html#variables-with-more-than-two-possible-outcomes"><i class="fa fa-check"></i><b>8.1.2</b> Variables with More than Two Possible Outcomes</a></li>
</ul></li>
<li class="chapter" data-level="8.2" data-path="categorical-data-analysis.html"><a href="categorical-data-analysis.html#introduction-to-tests-for-association-for-two-categorical-variables"><i class="fa fa-check"></i><b>8.2</b> Introduction to Tests for Association for Two Categorical Variables</a>
<ul>
<li class="chapter" data-level="8.2.1" data-path="categorical-data-analysis.html"><a href="categorical-data-analysis.html#x-2-tables"><i class="fa fa-check"></i><b>8.2.1</b> 2 x 2 Tables</a></li>
<li class="chapter" data-level="8.2.2" data-path="categorical-data-analysis.html"><a href="categorical-data-analysis.html#nominal-explanatory-and-response-variables"><i class="fa fa-check"></i><b>8.2.2</b> Nominal Explanatory and Response Variables</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="9" data-path="regression-models.html"><a href="regression-models.html"><i class="fa fa-check"></i><b>9</b> Regression Models</a>
<ul>
<li class="chapter" data-level="9.1" data-path="regression-models.html"><a href="regression-models.html#simple-linear-regression"><i class="fa fa-check"></i><b>9.1</b> Simple Linear Regression</a>
<ul>
<li class="chapter" data-level="9.1.1" data-path="regression-models.html"><a href="regression-models.html#estimation-of-model-parameters"><i class="fa fa-check"></i><b>9.1.1</b> Estimation of Model Parameters</a></li>
<li class="chapter" data-level="9.1.2" data-path="regression-models.html"><a href="regression-models.html#inference-regarding-beta_1-and-beta_0"><i class="fa fa-check"></i><b>9.1.2</b> Inference Regarding <span class="math inline">\(\beta_1\)</span> and <span class="math inline">\(\beta_0\)</span></a></li>
<li class="chapter" data-level="9.1.3" data-path="regression-models.html"><a href="regression-models.html#estimating-a-mean-and-predicting-a-new-observation-xx"><i class="fa fa-check"></i><b>9.1.3</b> Estimating a Mean and Predicting a New Observation @ <span class="math inline">\(X=X^*\)</span></a></li>
<li class="chapter" data-level="9.1.4" data-path="regression-models.html"><a href="regression-models.html#analysis-of-variance"><i class="fa fa-check"></i><b>9.1.4</b> Analysis of Variance</a></li>
<li class="chapter" data-level="9.1.5" data-path="regression-models.html"><a href="regression-models.html#correlation"><i class="fa fa-check"></i><b>9.1.5</b> Correlation</a></li>
</ul></li>
<li class="chapter" data-level="9.2" data-path="regression-models.html"><a href="regression-models.html#multiple-linear-regression"><i class="fa fa-check"></i><b>9.2</b> Multiple Linear Regression</a>
<ul>
<li class="chapter" data-level="9.2.1" data-path="regression-models.html"><a href="regression-models.html#testing-and-estimation-for-partial-regression-coefficients"><i class="fa fa-check"></i><b>9.2.1</b> Testing and Estimation for Partial Regression Coefficients</a></li>
<li class="chapter" data-level="9.2.2" data-path="regression-models.html"><a href="regression-models.html#analysis-of-variance-1"><i class="fa fa-check"></i><b>9.2.2</b> Analysis of Variance</a></li>
<li class="chapter" data-level="9.2.3" data-path="regression-models.html"><a href="regression-models.html#testing-a-subset-of-betas-0"><i class="fa fa-check"></i><b>9.2.3</b> Testing a Subset of <span class="math inline">\(\beta^s = 0\)</span></a></li>
<li class="chapter" data-level="9.2.4" data-path="regression-models.html"><a href="regression-models.html#models-with-categorical-qualitative-predictors"><i class="fa fa-check"></i><b>9.2.4</b> Models With Categorical (Qualitative) Predictors</a></li>
<li class="chapter" data-level="9.2.5" data-path="regression-models.html"><a href="regression-models.html#models-with-interaction-terms"><i class="fa fa-check"></i><b>9.2.5</b> Models With Interaction Terms</a></li>
</ul></li>
<li class="chapter" data-level="9.3" data-path="regression-models.html"><a href="regression-models.html#logistic-regression"><i class="fa fa-check"></i><b>9.3</b> Logistic Regression</a></li>
</ul></li>
<li class="divider"></li>
<li><a href="https://github.com/rstudio/bookdown" target="blank">Published with bookdown</a></li>

</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">Statistics and the Physical World</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="inferences-for-population-means" class="section level1 hasAnchor" number="4">
<h1><span class="header-section-number">Chapter 4</span> Inferences for Population Means<a href="inferences-for-population-means.html#inferences-for-population-means" class="anchor-section" aria-label="Anchor link to header"></a></h1>
<p>Researchers often are interested in making statements regarding unknown population means and medians based on sample data.
There are two common methods for making inferences: <strong>Estimation</strong> and <strong>Hypothesis Testing</strong>. The two methods are related and
make use of the sampling distribution of the sample mean when making statements regarding the population mean.</p>
<p>Estimation can provide a single “best” prediction of the population mean, a <strong>point estimate</strong>, or it can provide a range of
values that hopefully encompass the true population mean, an <strong>interval estimate</strong>. Hypothesis testing involves setting an a priori (null)
value for the unknown population mean, and measuring the extent to which the sample data contradict that value. Note that a confidence interval
provides a credible set of values for the unknown population mean, and can be used to test whether or not the population mean is the null value.
Both methods involve uncertainty as we are making statements regarding a population based on sample data.</p>
<div id="estimation" class="section level2 hasAnchor" number="4.1">
<h2><span class="header-section-number">4.1</span> Estimation<a href="inferences-for-population-means.html#estimation" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>For large samples, the sample mean has an approximately normal sampling distribution centered at the population mean, <span class="math inline">\(\mu\)</span>, and a standard error
<span class="math inline">\(\sigma/\sqrt{n}\)</span>. When the data are normally distributed, the sampling distribution is normal for all sample sizes. For normal distributions,
95% of its density lies in the range (mean +/- 1.96 SD). Thus, when we take a random sample, we obtain the following probability statement
regarding the sample mean.</p>
<p><span class="math display">\[ \overline{Y} \stackrel{\cdot}{\sim} N\left(\mu, SE\{\overline{Y}\}=\frac{\sigma}{\sqrt{n}}\right) \quad \Rightarrow \quad
P\left(\mu-z_{\alpha/2}\frac{\sigma}{\sqrt{n}} \leq \overline{Y} \leq \mu+z_{\alpha/2}\frac{\sigma}{\sqrt{n}}\right) \approx 1-\alpha\]</span></p>
<p><span class="math display">\[\mbox{ where } P\left(Z \geq z_a\right) = a \]</span></p>
<p><span class="math display">\[ \Rightarrow \quad 1-\alpha \approx P\left(-z_{\alpha/2} \leq \frac{\overline{Y} - \mu}{\sigma/\sqrt{n}} \leq z_{\alpha/2}\right) = P\left(\overline{Y}-z_{\alpha/2}\frac{\sigma}{\sqrt{n}} \leq \mu \leq \overline{Y}+z_{\alpha/2}\frac{\sigma}{\sqrt{n}}\right)  \]</span></p>
<p>Some commonly used coverage probabilities <span class="math inline">\((1-\alpha)\)</span> are given here, along with the corresponding <span class="math inline">\(z\)</span> values.</p>
<p><span class="math display">\[  1-\alpha=.90 \quad \Rightarrow  \quad \alpha=.10 \quad\Rightarrow \quad\frac{\alpha}{2}=.05 \quad \Rightarrow \quad z_{.05}=1.645 \]</span>
<span class="math display">\[1-\alpha=.95 \quad \Rightarrow \quad z_{.025}=1.96 \qquad
1-\alpha=.99 \quad \Rightarrow \quad  z_{.005}=2.576 \]</span></p>
<p>Note that in the probability statements above, <span class="math inline">\(\mu\)</span> is a fixed, unknown constant in practice, and <span class="math inline">\(\overline{Y}\)</span> is a random variable that varies from
sample to sample. The probability refers to the fraction of the samples that will provide sample means such that the lower and upper bounds
“cover” <span class="math inline">\(\mu\)</span>. Also, in practice, <span class="math inline">\(\sigma\)</span> will be unknown and need to be replaced by the sample standard deviation.</p>
<p>A Large-Sample <span class="math inline">\((1-\alpha)100\%\)</span> Confidence Interval for a Population Mean <span class="math inline">\(\mu\)</span> is given below, where <span class="math inline">\(\overline{y}\)</span> and <span class="math inline">\(s\)</span> are the observed mean and standard deviation
from a random sample of size <span class="math inline">\(n\)</span> and <span class="math inline">\(\widehat{SE}\{\overline{Y}\}\)</span> represents the <strong>estimated standard error</strong> of the sample mean.</p>
<p><span class="math display">\[ \overline{y} \pm z_{\alpha/2} \widehat{SE}\{\overline{Y}\} \qquad \qquad \overline{y} \pm z_{\alpha/2}\frac{s}{\sqrt{n}}  \]</span></p>
<p>When the data are normally distributed, for small samples (although this has shown to work well for other distributions), replace <span class="math inline">\(z_{\alpha/2}\)</span>
with <span class="math inline">\(t_{\alpha/2, n-1}\)</span>.</p>
<p><span class="math display">\[ \overline{y} \pm t_{\alpha/2, n-1} \widehat{SE}\{\overline{Y}\} \qquad \qquad \overline{y} \pm t_{\alpha/2, n-1}\frac{s}{\sqrt{n}}  \]</span></p>
<p>Any software package or spreadsheet that is used to obtain a confidence interval for a mean (or difference between two means) will always
use the version based on the <span class="math inline">\(t\)</span>-distribution.
There will be settings, when making confidence intervals for parameters, that there is no justification for using the <span class="math inline">\(t\)</span>-distribution, and
we will make use the <span class="math inline">\(z\)</span>-distribution, as do statistical software packages.</p>
<p><strong>Example 4.1: NHL Players’ BMI</strong></p>
<p>The Body Mass Indices for the 2014/5 NHL players are approximately normally distributed with mean <span class="math inline">\(\mu=26.514\)</span> and standard deviation <span class="math inline">\(\sigma=1.449\)</span>.
We take 10000 random samples of size <span class="math inline">\(n=12\)</span>, implying a standard error of <span class="math inline">\(\sigma_{\overline{Y}}=1.449/\sqrt{12}=0.418\)</span>. We count the number of the 10000
sample means that lie in the ranges <span class="math inline">\(\mu \pm z_{\alpha/2}\sigma_{\overline{Y}}\)</span> for the three values of <span class="math inline">\(1-\alpha\)</span> given above. The results are given in Table <a href="inferences-for-population-means.html#tab:nhlbmi4a">4.1</a>.</p>
<table>
<caption><span id="tab:nhlbmi4a">Table 4.1: </span>Coverage rates for z- and t-based Confidence Intervals for NHL BMI</caption>
<thead>
<tr class="header">
<th align="left"></th>
<th align="right">90% Confidence</th>
<th align="right">95% Confidence</th>
<th align="right">99% Confidence</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">Z - True SE</td>
<td align="right">0.9014</td>
<td align="right">0.9512</td>
<td align="right">0.9820</td>
</tr>
<tr class="even">
<td align="left">Z - Estimated SE</td>
<td align="right">0.8754</td>
<td align="right">0.9297</td>
<td align="right">0.9649</td>
</tr>
<tr class="odd">
<td align="left">t - Estimated SE</td>
<td align="right">0.9045</td>
<td align="right">0.9545</td>
<td align="right">0.9920</td>
</tr>
</tbody>
</table>
<p>Of the 10000 sample means, 9014 (90.14%) lied within <span class="math inline">\(\mu \pm 1.645(.418)\)</span>, 9512 (95.12%) within <span class="math inline">\(\mu \pm 1.96(.418)\)</span>, and
9820 (98.20%) within <span class="math inline">\(\mu \pm 2.576(.418)\)</span>. Had we constructed intervals of the form <span class="math inline">\(\overline{y} \pm z_{\alpha/2}(.420)\)</span> for each
sample mean, the coverage rates for <span class="math inline">\(\mu\)</span> would have been the same values (90.14%, 95.12%, 98.20%).</p>
<p>When the population standard error <span class="math inline">\(SE\{\overline{Y}\}=\sigma/\sqrt{n}\)</span> is replaced by the estimated standard error <span class="math inline">\(\widehat{SE}\{\overline{Y}\}=s/\sqrt{n}\)</span>,
which varies from sample to sample, we find the coverage rates of the intervals decrease. When constructing intervals of the form
<span class="math inline">\(\overline{y} \pm z_{\alpha/2} s/\sqrt{n}\)</span>, the coverage rates fall to 87.54%, 92.97%, and 96.49%, respectively. This is a by-product of the fact that
the sampling distribution of the standard deviation is skewed right, and its median is below its mean. Whenever the sample standard deviation
is small, the width of the constructed interval is shortened.</p>
<p>When using the estimated standard error, replace <span class="math inline">\(z_{\alpha/2}\)</span> with the
corresponding critical value for the <span class="math inline">\(t\)</span>-distribution, with <span class="math inline">\(n-1\)</span> degrees of freedom: <span class="math inline">\(t_{\alpha/2,n-1}\)</span>. For this case, with <span class="math inline">\(n=12\)</span>, we obtain
<span class="math inline">\(t_{.05,11}=1.796\)</span>, <span class="math inline">\(t_{.025,11}=2.201\)</span>, and <span class="math inline">\(t_{.005,11}=3.106\)</span>. When <span class="math inline">\(z\)</span> is replaced by the corresponding <span class="math inline">\(t\)</span> values, the coverage rates
for the constructed intervals with the estimated standard errors reach their nominal rates: 90.45%, 95.45%, and 99.20%, respectively.</p>
<p>For the first random sample of the 10000 generated, we observe <span class="math inline">\(\overline{y}=27.140\)</span> and <span class="math inline">\(s=1.429\)</span>. The 95% Confidence Interval for <span class="math inline">\(\mu\)</span> based on the first
sample is obtained as follows.</p>
<p><span class="math display">\[ \overline{y} \pm t_{.025,n-1}\frac{s}{\sqrt{n}}  \equiv  27.140 \pm 2.201\left(\frac{1.429}{\sqrt{12}}\right)
\equiv  27.140 \pm 0.908 \equiv (26.232 , 28.048) \]</span></p>
<p>Thus, this interval does contain <span class="math inline">\(\mu = 26.514\)</span>.</p>
<p><span class="math display">\[ \nabla  \]</span></p>
<p>Often, researchers choose the sample size so that the <strong>margin of error</strong> will not exceed some fixed level <span class="math inline">\(E\)</span> with high confidence.
That is, we want the difference between the sample and population means to be within <span class="math inline">\(E\)</span> with confidence level <span class="math inline">\(1-\alpha\)</span>. This means
the width of a <span class="math inline">\((1-\alpha)100\%\)</span> Confidence Interval will be <span class="math inline">\(2E\)</span>. This can be done in one calculation based on using the <span class="math inline">\(z\)</span> distribution,
or more conservatively, by trivial iteration based on the <span class="math inline">\(t\)</span>-distribution. Either way, we must have an approximation of <span class="math inline">\(\sigma\)</span> based on previous
research or a pilot study.</p>
<p><span class="math display">\[ z: \quad E = z_{\alpha/2} \frac{\sigma}{\sqrt{n}} \quad \Rightarrow \quad n=\left(\frac{z_{\alpha/2} \sigma}{E}\right)^2 \]</span>
<span class="math display">\[ t: \mbox{Smallest }n \mbox{ such that } E \leq t_{\alpha/2, n-1} \frac{\sigma}{\sqrt{n}}  \]</span></p>
<p><strong>Example 4.2: Estimating Population Mean Male Rock and Roll Marathon Speed</strong></p>
<p>Suppose we want to estimate the population mean of the male Rock and Roll marathon running speeds within <span class="math inline">\(E=0.20\)</span> miles per hour with 95%
confidence. We treat the standard deviation as known, <span class="math inline">\(\sigma=1.058\)</span>. The calculation for the sample size based on the <span class="math inline">\(z\)</span>-distribution is given below,
followed by R commands that iteratively solve for <span class="math inline">\(n\)</span> based on the <span class="math inline">\(t\)</span>-distribution.</p>
<p><span class="math display">\[ z: \quad z_{.025} = 1.96 \quad n=\left(\frac{1.96(1.058)}{0.20}\right)^2=107.5 \approx 108\]</span></p>
<pre><code>##        n       E.t
## [1,] 110 0.1999336</code></pre>
<p>Since <span class="math inline">\(n\)</span> was needed to be so large, <span class="math inline">\(z_{.025}\)</span> and <span class="math inline">\(t_{.025,n-1}\)</span> are very close, and both methods give virtually the same <span class="math inline">\(n\)</span> (108 and 110).</p>
</div>
<div id="hypothesis-testing" class="section level2 hasAnchor" number="4.2">
<h2><span class="header-section-number">4.2</span> Hypothesis Testing<a href="inferences-for-population-means.html#hypothesis-testing" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>In hypothesis testing, a sample of data is used to determine whether a population mean is equal to some pre-specified level <span class="math inline">\(\mu_0\)</span>. It is
rare, except in some situations to test whether the mean is some specific value based on historical level, or government or corporate specified level
to have a null value to test.
These tests are more common when comparing two or more populations or treatments and determining whether their means are equal. The elements
of a hypothesis test are given below.</p>
<ul>
<li><strong>Null Hypothesis <span class="math inline">\((H_0)\)</span></strong> - Statement regarding a parameter that is to be tested. It always includes an equality, and the test is conducted assuming its truth.</li>
<li><strong>Alternative (Research) Hypothesis <span class="math inline">\((H_A)\)</span></strong> - Statement that contradicts the null hypothesis. Includes “greater than” <span class="math inline">\((&gt;)\)</span>, “less than” <span class="math inline">\((&lt;)\)</span>,or “not equal to” <span class="math inline">\((\neq)\)</span></li>
<li><strong>Test Statistic (T.S.)</strong> - A statistic measuring the discrepancy between the sample statistic and the parameter value under the null hypothesis (where the equality holds).</li>
<li><strong>Rejection Region (R.R.)</strong> - Values of the Test Statistic for which the Null Hypothesis is rejected. Depends on the significance level of the test.</li>
<li><strong>p-value</strong> - Probability under the null hypothesis (at the equality) of observing a Test Statistic as extreme or more extreme than the observed Test Statistic. Also known as the observed significance level.</li>
<li><strong>Type I Error</strong> - Rejecting the Null Hypothesis when in fact it is true. The Rejection Region is chosen so that this has a particular small probability (<span class="math inline">\(\alpha=P(\mbox{Type I Error})\)</span> is the <strong>significance level</strong> and is often set at 0.05).</li>
<li><strong>Type II Error</strong> - Failing to reject the Null Hypothesis when it is false. Depends on the true value of the parameter. Sample size is often selected so that it has a particular small probability for an important difference. <span class="math inline">\(\beta=P(\mbox{Type II Error})\)</span>.</li>
<li><strong>Power</strong> - The probability the Null Hypothesis is rejected. When <span class="math inline">\(H_0\)</span> is true the power is <span class="math inline">\(\pi=\alpha\)</span>, when <span class="math inline">\(H_A\)</span> is true, it is <span class="math inline">\(\pi=1-\beta\)</span>.</li>
</ul>
<p>The testing procedure for a mean is based on the sampling distribution of <span class="math inline">\(\overline{Y}\)</span> being approximately normal with mean <span class="math inline">\(\mu_0\)</span> under the null hypothesis.
Also, when the data are normal the difference between the sample mean and <span class="math inline">\(\mu_0\)</span> divided by its estimated standard error is distributed
as <span class="math inline">\(t\)</span> with <span class="math inline">\(n-1\)</span> degrees of freedom under the null hypothesis.</p>
<p><span class="math display">\[ \overline{Y} \stackrel{\cdot}{\sim} N\left(\mu_0,SE\{\overline{Y}\}=\frac{\sigma}{\sqrt{n}}\right) \qquad \qquad
\frac{\overline{Y}-\mu_0}{\widehat{SE}\{\overline{Y}\}}=\frac{\overline{Y}-\mu_0}{s/\sqrt{n}} \sim t_{n-1} \]</span></p>
<p>When the absolute value of the <span class="math inline">\(t\)</span>-statistic is large, there is evidence against the null hypothesis. Once a sample is taken (observed),
and the sample mean <span class="math inline">\(\overline{y}\)</span> and sample standard deviation <span class="math inline">\(s\)</span> are observed, the test is conducted as follows for
2-tailed, upper tailed, and lower tailed alternatives.</p>
<p><span class="math display">\[ \mbox{2-tailed: } H_0: \mu=\mu_0 \qquad H_A: \mu \neq \mu_0 \qquad \mbox{T.S.: } t_{obs}=\frac{\overline{y} - \mu_0}{s/\sqrt{n}} \]</span>
<span class="math display">\[\mbox{R.R.: } |t_{obs}| \geq t_{\alpha/2, n-1} \qquad P=2P\left(t_{n-1} \geq |t_{obs}|\right) \]</span></p>
<p><span class="math display">\[ \mbox{Upper tailed: } H_0: \mu \leq\mu_0 \qquad H_A: \mu &gt; \mu_0 \qquad \mbox{T.S.: } t_{obs}=\frac{\overline{y} - \mu_0}{s/\sqrt{n}}\]</span>
<span class="math display">\[\mbox{R.R.: } t_{obs} \geq t_{\alpha, n-1} \qquad P=P\left(t_{n-1} \geq t_{obs}\right) \]</span></p>
<p><span class="math display">\[ \mbox{Lower tailed: } H_0: \mu \geq\mu_0 \qquad H_A: \mu &lt; \mu_0 \qquad \mbox{T.S.: } t_{obs}=\frac{\overline{y} - \mu_0}{s/\sqrt{n}} \]</span>
<span class="math display">\[\mbox{R.R.: } t_{obs} \leq -t_{\alpha, n-1} \qquad P=P\left(t_{n-1} \leq t_{obs}\right) \]</span></p>
<p>The form of the rejection regions are given for 2-tailed, Upper and Lower tailed tests in Figure <a href="inferences-for-population-means.html#fig:rrmar4b">4.1</a>. These are based on
<span class="math inline">\(\alpha=0.05\)</span>, and <span class="math inline">\(n=16\)</span>. The vertical lines lie at <span class="math inline">\(t_{.975,15}=-t_{.025,15}=-2.131\)</span> and <span class="math inline">\(t_{.025,15}=2.131\)</span> for the 2-tailed test,
<span class="math inline">\(t_{.05,15}=1.753\)</span> for the Upper tailed test, and <span class="math inline">\(t_{.95,15}=-t_{.05,15}=-1.753\)</span> for the Lower tailed test.</p>
<div class="figure" style="text-align: center"><span style="display:block;" id="fig:rrmar4b"></span>
<img src="STA2170bookdownproj_files/figure-html/rrmar4b-1.png" alt="Rejection Regions for Test Statistics with n=16" width="80%" />
<p class="caption">
Figure 4.1: Rejection Regions for Test Statistics with n=16
</p>
</div>
<p>When the Null Hypothesis is false, the test statistic is distributed as non-central <span class="math inline">\(t\)</span> with non-centrality parameter given below.</p>
<p><span class="math display">\[ H_0: \mu=\mu_0    \qquad  \mbox{In reality: } \mu=\mu_A \neq \mu_0  \qquad \Delta = \frac{\mu_A-\mu_0}{\sigma/\sqrt{n}}  \qquad
t=\frac{\overline{Y}-\mu_0}{S/\sqrt{n}} \stackrel{\cdot}{\sim} t_{n-1,\Delta} \]</span></p>
<p>Power probabilities, which depend on whether the test is 2-tailed or 1-tailed can be obtained from statistical software packages, such as R,
but not directly in EXCEL.</p>
<p><span class="math display">\[ \mbox{2-tailed tests: } \pi = P\left(t_{n-1,\Delta} \leq -t_{\alpha/2,n-1}\right) + P\left(t_{n-1,\Delta} \geq t_{\alpha/2,n-1}\right) \]</span></p>
<p><span class="math display">\[ \mbox{Lower tailed tests: } \pi = P\left(t_{n-1,\Delta} \leq -t_{\alpha,n-1}\right) \]</span>
<span class="math display">\[  \mbox{Upper tailed tests: } \pi = P\left(t_{n-1,\Delta} \geq t_{\alpha,n-1}\right) \]</span></p>
<p>While it is rare to use hypothesis testing regarding a single mean (except in the case where data are paired differences within individual units),
the procedure is demonstrated based on male Rock and Roll marathon speeds with several values of <span class="math inline">\(\mu_0\)</span>.</p>
<p><strong>Example 4.3: Male Rock and Roll Marathon Speeds</strong></p>
<p>For the males participating in the Rock and Roll marathon, the population mean speed was <span class="math inline">\(\mu=6.337\)</span> miles per hour with standard
deviation of <span class="math inline">\(\sigma=1.058\)</span>. We will demonstrate
hypothesis testing regarding a single mean by first testing <span class="math inline">\(H_0:\mu=6.337\)</span> versus <span class="math inline">\(H_A:\mu \neq 6.337\)</span>, based on random samples of <span class="math inline">\(n=40\)</span>. Since the
null hypothesis is true, if the test is conducted with a Type I Error rate of <span class="math inline">\(\alpha=0.05\)</span>, the test should reject the null in approximately 5% of samples.
The distribution of the test statistic is <span class="math inline">\(t\)</span> with <span class="math inline">\(n-1=39\)</span> degrees of freedom.
Further, the p-values should approximate a Uniform distribution between 0 and 1.</p>
<pre><code>##   Runner Gender Place Seconds      mph
## 1      1      M  1830   17375 5.432374
## 2      2      F  2475   20988 4.497213</code></pre>
<pre><code>## [1] 0.0482</code></pre>
<div class="figure" style="text-align: center"><span style="display:block;" id="fig:rrmar4c"></span>
<img src="STA2170bookdownproj_files/figure-html/rrmar4c-1.png" alt="Distributions of t-statistics and P-values when the null hypothesis is true. Male Rock and Roll Marathon velocities with n=40" width="80%" />
<p class="caption">
Figure 4.2: Distributions of t-statistics and P-values when the null hypothesis is true. Male Rock and Roll Marathon velocities with n=40
</p>
</div>
<p>Note that 482 (4.82%) of the 10000 samples reject the null hypothesis,
in agreement with what is to be expected. A histogram of the observed test statistics, along with the <span class="math inline">\(t\)</span>-density, and the p-values and the the Uniform
density are given in Figure <a href="inferences-for-population-means.html#fig:rrmar4c">4.2</a>. The two vertical bars on the <span class="math inline">\(t\)</span>-statistic plot are at <span class="math inline">\(\pm t_{.025,39} = \pm 2.023\)</span>.</p>
<p>Next consider cases where the null hypothesis is not true. Consider <span class="math inline">\(H_{01}:\mu=6\)</span> versus <span class="math inline">\(H_{A1}:\mu \neq 6\)</span> and<br />
<span class="math inline">\(H_{02}:\mu=6.5\)</span> versus <span class="math inline">\(H_{A2}:\mu \neq 6.5\)</span>. Since the null value for <span class="math inline">\(H_{02}\)</span> is closer to the true value <span class="math inline">\(\mu_A=6.337\)</span> than the null value
for <span class="math inline">\(H_{01}\)</span>, we expect that we will reject <span class="math inline">\(H_{02}\)</span> less often for tests based on the same sample size. That is, the power is higher for <span class="math inline">\(H_{01}\)</span> than <span class="math inline">\(H_{02}\)</span>.
The non-centrality parameters and the corresponding power values are given below, based on samples of <span class="math inline">\(n=40\)</span>.</p>
<p><span class="math display">\[ \Delta_1= \frac{6.337-6.0}{1.058/\sqrt{40}} = 2.015 \qquad \pi_1=
P\left(t_{39,2.015}\leq -2.23\right)+P\left(t_{39,2.015}\geq2.23\right)
=.5022 \]</span>
<span class="math display">\[\Delta_2= \frac{6.337-6.5}{1.058/\sqrt{40}} = -0.974 \qquad \pi_2\left(t_{39,-0.974}\leq -2.23\right)+P\left(t_{39,-0.974}\geq2.23\right)
=.1583\]</span></p>
<p>Results of the observed power are given in Table <a href="inferences-for-population-means.html#tab:rrmar4d">4.2</a>.</p>
<pre><code>##   Runner Gender Place Seconds      mph
## 1      1      M  1830   17375 5.432374
## 2      2      F  2475   20988 4.497213</code></pre>
<table>
<caption><span id="tab:rrmar4d">Table 4.2: </span>Power of t-test for various null values of mu</caption>
<thead>
<tr class="header">
<th align="left"></th>
<th align="right">mu0</th>
<th align="right">Delta</th>
<th align="right">Theoretical Power</th>
<th align="right">Empirical Power</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">mu0=6.337</td>
<td align="right">6.337</td>
<td align="right">0.000</td>
<td align="right">0.050</td>
<td align="right">0.048</td>
</tr>
<tr class="even">
<td align="left">mu0=6</td>
<td align="right">6.000</td>
<td align="right">2.015</td>
<td align="right">0.502</td>
<td align="right">0.489</td>
</tr>
<tr class="odd">
<td align="left">mu0=6.5</td>
<td align="right">6.500</td>
<td align="right">-0.975</td>
<td align="right">0.158</td>
<td align="right">0.176</td>
</tr>
</tbody>
</table>
<div class="figure" style="text-align: center"><span style="display:block;" id="fig:rrmar4d"></span>
<img src="STA2170bookdownproj_files/figure-html/rrmar4d-1.png" alt="Distribution of t-statistics when the null hypothesis is false. Male Rock and Roll Marathon velocities with n=40, mu0=6" width="80%" />
<p class="caption">
Figure 4.3: Distribution of t-statistics when the null hypothesis is false. Male Rock and Roll Marathon velocities with n=40, mu0=6
</p>
</div>
<p>Based on 10000 random samples from the male marathon speeds, 49.93% rejected <span class="math inline">\(H_0:\mu=6\)</span>, and for another set of 10000 random samples, 17.05%
rejected <span class="math inline">\(H_0:\mu=6.5\)</span>. The histogram of the test statistics and the non-central <span class="math inline">\(t\)</span>-distribution are given
in Figure <a href="inferences-for-population-means.html#fig:rrmar4d">4.3</a> for testing <span class="math inline">\(H_0:\mu=6\)</span>.</p>
<p><span class="math display">\[ \nabla  \]</span></p>

<div class="sourceCode" id="cb43"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb43-1"><a href="inferences-for-population-means.html#cb43-1" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span>
<span id="cb43-2"><a href="inferences-for-population-means.html#cb43-2" tabindex="-1"></a><span class="fu">library</span>(kableExtra)</span></code></pre></div>
</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="probability.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="introduction-to-experimentation.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
  "sharing": {
    "github": false,
    "facebook": true,
    "twitter": true,
    "linkedin": false,
    "weibo": false,
    "instapaper": false,
    "vk": false,
    "whatsapp": false,
    "all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
  },
  "fontsettings": {
    "theme": "white",
    "family": "sans",
    "size": 2
  },
  "edit": {
    "link": null,
    "text": null
  },
  "history": {
    "link": null,
    "text": null
  },
  "view": {
    "link": null,
    "text": null
  },
  "download": null,
  "search": {
    "engine": "fuse",
    "options": null
  },
  "toc": {
    "collapse": "subsection",
    "link": "https://github.com/LarryWinner/STA2170-Notes1/edit/main/%s",
    "text": "Edit"
  }
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.9/latest.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
