<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>Chapter 9 Regression Models | Statistics and the Physical World</title>
  <meta name="description" content="This is an Introduction to Statistics with applications from the physical world. We will make use of the R programming language for computations." />
  <meta name="generator" content="bookdown 0.43 and GitBook 2.6.7" />

  <meta property="og:title" content="Chapter 9 Regression Models | Statistics and the Physical World" />
  <meta property="og:type" content="book" />
  
  <meta property="og:description" content="This is an Introduction to Statistics with applications from the physical world. We will make use of the R programming language for computations." />
  <meta name="github-repo" content="rstudio/bookdown-demo" />

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Chapter 9 Regression Models | Statistics and the Physical World" />
  
  <meta name="twitter:description" content="This is an Introduction to Statistics with applications from the physical world. We will make use of the R programming language for computations." />
  

<meta name="author" content="Larry Winner" />


<meta name="date" content="2026-06-22" />

  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="categorical-data-analysis.html"/>

<script src="libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/fuse.js@6.4.6/dist/fuse.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />








<link href="libs/anchor-sections-1.1.0/anchor-sections.css" rel="stylesheet" />
<link href="libs/anchor-sections-1.1.0/anchor-sections-hash.css" rel="stylesheet" />
<script src="libs/anchor-sections-1.1.0/anchor-sections.js"></script>


<style type="text/css">
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { color: #008000; } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { color: #008000; font-weight: bold; } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

<style type="text/css">
  
  div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
</style>
<style type="text/css">
/* Used with Pandoc 2.11+ new --citeproc when CSL is used */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
  margin-bottom: 0em;
}
.hanging div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}
</style>

<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">STA2170 Notes</a></li>

<li class="divider"></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i>Preface</a></li>
<li class="chapter" data-level="1" data-path="intro.html"><a href="intro.html"><i class="fa fa-check"></i><b>1</b> Introduction</a>
<ul>
<li class="chapter" data-level="1.1" data-path="intro.html"><a href="intro.html#basic-concepts-of-statistical-analysis"><i class="fa fa-check"></i><b>1.1</b> Basic Concepts of Statistical Analysis</a></li>
<li class="chapter" data-level="1.2" data-path="intro.html"><a href="intro.html#data-collection"><i class="fa fa-check"></i><b>1.2</b> Data Collection</a></li>
<li class="chapter" data-level="1.3" data-path="intro.html"><a href="intro.html#variable-types"><i class="fa fa-check"></i><b>1.3</b> Variable Types</a></li>
</ul></li>
<li class="chapter" data-level="2" data-path="describing-data.html"><a href="describing-data.html"><i class="fa fa-check"></i><b>2</b> Describing Data</a>
<ul>
<li class="chapter" data-level="2.1" data-path="describing-data.html"><a href="describing-data.html#graphical-description-of-a-single-variable"><i class="fa fa-check"></i><b>2.1</b> Graphical Description of a Single Variable</a></li>
<li class="chapter" data-level="2.2" data-path="describing-data.html"><a href="describing-data.html#numerical-descriptive-measures-of-a-single-variable"><i class="fa fa-check"></i><b>2.2</b> Numerical Descriptive Measures of a Single Variable</a>
<ul>
<li class="chapter" data-level="2.2.1" data-path="describing-data.html"><a href="describing-data.html#measures-of-central-tendency"><i class="fa fa-check"></i><b>2.2.1</b> Measures of Central Tendency</a></li>
<li class="chapter" data-level="2.2.2" data-path="describing-data.html"><a href="describing-data.html#measures-of-variability"><i class="fa fa-check"></i><b>2.2.2</b> Measures of Variability</a></li>
</ul></li>
<li class="chapter" data-level="2.3" data-path="describing-data.html"><a href="describing-data.html#describing-more-than-one-variable"><i class="fa fa-check"></i><b>2.3</b> Describing More than One Variable</a></li>
</ul></li>
<li class="chapter" data-level="3" data-path="probability.html"><a href="probability.html"><i class="fa fa-check"></i><b>3</b> Probability</a>
<ul>
<li class="chapter" data-level="3.1" data-path="probability.html"><a href="probability.html#terminology-and-probability-rules"><i class="fa fa-check"></i><b>3.1</b> Terminology and Probability Rules</a></li>
<li class="chapter" data-level="3.2" data-path="probability.html"><a href="probability.html#basic-probability"><i class="fa fa-check"></i><b>3.2</b> Basic Probability</a>
<ul>
<li class="chapter" data-level="3.2.1" data-path="probability.html"><a href="probability.html#bayes-rule"><i class="fa fa-check"></i><b>3.2.1</b> Bayes’ Rule</a></li>
</ul></li>
<li class="chapter" data-level="3.3" data-path="probability.html"><a href="probability.html#random-variables-and-probability-distributions"><i class="fa fa-check"></i><b>3.3</b> Random Variables and Probability Distributions</a></li>
<li class="chapter" data-level="3.4" data-path="probability.html"><a href="probability.html#discrete-random-variables"><i class="fa fa-check"></i><b>3.4</b> Discrete Random Variables</a>
<ul>
<li class="chapter" data-level="3.4.1" data-path="probability.html"><a href="probability.html#population-numerical-descriptive-measures"><i class="fa fa-check"></i><b>3.4.1</b> Population Numerical Descriptive Measures</a></li>
<li class="chapter" data-level="3.4.2" data-path="probability.html"><a href="probability.html#common-families-of-discrete-probability-distributions"><i class="fa fa-check"></i><b>3.4.2</b> Common Families of Discrete Probability Distributions</a></li>
</ul></li>
<li class="chapter" data-level="3.5" data-path="probability.html"><a href="probability.html#continuous-random-variables"><i class="fa fa-check"></i><b>3.5</b> Continuous Random Variables</a>
<ul>
<li class="chapter" data-level="3.5.1" data-path="probability.html"><a href="probability.html#common-families-of-continuous-probability-distributions"><i class="fa fa-check"></i><b>3.5.1</b> Common Families of Continuous Probability Distributions</a></li>
</ul></li>
<li class="chapter" data-level="3.6" data-path="probability.html"><a href="probability.html#sampling-distributions-and-the-central-limit-theorem"><i class="fa fa-check"></i><b>3.6</b> Sampling Distributions and the Central Limit Theorem</a></li>
</ul></li>
<li class="chapter" data-level="4" data-path="inferences-for-population-means.html"><a href="inferences-for-population-means.html"><i class="fa fa-check"></i><b>4</b> Inferences for Population Means</a>
<ul>
<li class="chapter" data-level="4.1" data-path="inferences-for-population-means.html"><a href="inferences-for-population-means.html#estimation"><i class="fa fa-check"></i><b>4.1</b> Estimation</a></li>
<li class="chapter" data-level="4.2" data-path="inferences-for-population-means.html"><a href="inferences-for-population-means.html#hypothesis-testing"><i class="fa fa-check"></i><b>4.2</b> Hypothesis Testing</a></li>
</ul></li>
<li class="chapter" data-level="5" data-path="introduction-to-experimentation.html"><a href="introduction-to-experimentation.html"><i class="fa fa-check"></i><b>5</b> Introduction to Experimentation</a></li>
<li class="chapter" data-level="6" data-path="comparing-two-population-means.html"><a href="comparing-two-population-means.html"><i class="fa fa-check"></i><b>6</b> Comparing Two Population Means</a>
<ul>
<li class="chapter" data-level="6.1" data-path="comparing-two-population-means.html"><a href="comparing-two-population-means.html#independent-samples"><i class="fa fa-check"></i><b>6.1</b> Independent Samples</a>
<ul>
<li class="chapter" data-level="6.1.1" data-path="comparing-two-population-means.html"><a href="comparing-two-population-means.html#large-sample-tests"><i class="fa fa-check"></i><b>6.1.1</b> Large-Sample tests</a></li>
<li class="chapter" data-level="6.1.2" data-path="comparing-two-population-means.html"><a href="comparing-two-population-means.html#small-sample-tests-with-normal-data"><i class="fa fa-check"></i><b>6.1.2</b> Small Sample Tests with Normal Data</a></li>
</ul></li>
<li class="chapter" data-level="6.2" data-path="comparing-two-population-means.html"><a href="comparing-two-population-means.html#paired-sample-designs"><i class="fa fa-check"></i><b>6.2</b> Paired Sample Designs</a></li>
<li class="chapter" data-level="6.3" data-path="comparing-two-population-means.html"><a href="comparing-two-population-means.html#nonparametric-tests"><i class="fa fa-check"></i><b>6.3</b> Nonparametric Tests</a>
<ul>
<li class="chapter" data-level="6.3.1" data-path="comparing-two-population-means.html"><a href="comparing-two-population-means.html#independent-samples---wilcoxon-rank-sum-test"><i class="fa fa-check"></i><b>6.3.1</b> Independent Samples - Wilcoxon Rank-Sum Test</a></li>
<li class="chapter" data-level="6.3.2" data-path="comparing-two-population-means.html"><a href="comparing-two-population-means.html#paired-samples---wilcoxon-signed-rank-test"><i class="fa fa-check"></i><b>6.3.2</b> Paired Samples - Wilcoxon Signed Rank Test</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="7" data-path="experimental-design-and-the-analysis-of-variance.html"><a href="experimental-design-and-the-analysis-of-variance.html"><i class="fa fa-check"></i><b>7</b> Experimental Design and the Analysis of Variance</a>
<ul>
<li class="chapter" data-level="7.1" data-path="experimental-design-and-the-analysis-of-variance.html"><a href="experimental-design-and-the-analysis-of-variance.html#completely-randomized-design-crd-for-independent-samples"><i class="fa fa-check"></i><b>7.1</b> Completely Randomized Design (CRD) For Independent Samples</a>
<ul>
<li class="chapter" data-level="7.1.1" data-path="experimental-design-and-the-analysis-of-variance.html"><a href="experimental-design-and-the-analysis-of-variance.html#analysis-of-variance-and-f-test-for-normal-data"><i class="fa fa-check"></i><b>7.1.1</b> Analysis of Variance and <span class="math inline">\(F\)</span>-Test for Normal Data</a></li>
<li class="chapter" data-level="7.1.2" data-path="experimental-design-and-the-analysis-of-variance.html"><a href="experimental-design-and-the-analysis-of-variance.html#comparisons-among-treatment-means"><i class="fa fa-check"></i><b>7.1.2</b> Comparisons among Treatment Means</a></li>
</ul></li>
<li class="chapter" data-level="7.2" data-path="experimental-design-and-the-analysis-of-variance.html"><a href="experimental-design-and-the-analysis-of-variance.html#randomized-block-design-rbd-for-studies-based-on-matched-units"><i class="fa fa-check"></i><b>7.2</b> Randomized Block Design (RBD) For Studies Based on Matched Units</a></li>
<li class="chapter" data-level="7.3" data-path="experimental-design-and-the-analysis-of-variance.html"><a href="experimental-design-and-the-analysis-of-variance.html#factorial-designs"><i class="fa fa-check"></i><b>7.3</b> Factorial Designs</a></li>
</ul></li>
<li class="chapter" data-level="8" data-path="categorical-data-analysis.html"><a href="categorical-data-analysis.html"><i class="fa fa-check"></i><b>8</b> Categorical Data Analysis</a>
<ul>
<li class="chapter" data-level="8.1" data-path="categorical-data-analysis.html"><a href="categorical-data-analysis.html#inference-concerning-a-single-variable"><i class="fa fa-check"></i><b>8.1</b> Inference Concerning a Single Variable</a>
<ul>
<li class="chapter" data-level="8.1.1" data-path="categorical-data-analysis.html"><a href="categorical-data-analysis.html#variables-with-two-possible-outcomes"><i class="fa fa-check"></i><b>8.1.1</b> Variables with Two Possible Outcomes</a></li>
<li class="chapter" data-level="8.1.2" data-path="categorical-data-analysis.html"><a href="categorical-data-analysis.html#variables-with-more-than-two-possible-outcomes"><i class="fa fa-check"></i><b>8.1.2</b> Variables with More than Two Possible Outcomes</a></li>
</ul></li>
<li class="chapter" data-level="8.2" data-path="categorical-data-analysis.html"><a href="categorical-data-analysis.html#introduction-to-tests-for-association-for-two-categorical-variables"><i class="fa fa-check"></i><b>8.2</b> Introduction to Tests for Association for Two Categorical Variables</a>
<ul>
<li class="chapter" data-level="8.2.1" data-path="categorical-data-analysis.html"><a href="categorical-data-analysis.html#x-2-tables"><i class="fa fa-check"></i><b>8.2.1</b> 2 x 2 Tables</a></li>
<li class="chapter" data-level="8.2.2" data-path="categorical-data-analysis.html"><a href="categorical-data-analysis.html#nominal-explanatory-and-response-variables"><i class="fa fa-check"></i><b>8.2.2</b> Nominal Explanatory and Response Variables</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="9" data-path="regression-models.html"><a href="regression-models.html"><i class="fa fa-check"></i><b>9</b> Regression Models</a>
<ul>
<li class="chapter" data-level="9.1" data-path="regression-models.html"><a href="regression-models.html#simple-linear-regression"><i class="fa fa-check"></i><b>9.1</b> Simple Linear Regression</a>
<ul>
<li class="chapter" data-level="9.1.1" data-path="regression-models.html"><a href="regression-models.html#estimation-of-model-parameters"><i class="fa fa-check"></i><b>9.1.1</b> Estimation of Model Parameters</a></li>
<li class="chapter" data-level="9.1.2" data-path="regression-models.html"><a href="regression-models.html#inference-regarding-beta_1-and-beta_0"><i class="fa fa-check"></i><b>9.1.2</b> Inference Regarding <span class="math inline">\(\beta_1\)</span> and <span class="math inline">\(\beta_0\)</span></a></li>
<li class="chapter" data-level="9.1.3" data-path="regression-models.html"><a href="regression-models.html#estimating-a-mean-and-predicting-a-new-observation-xx"><i class="fa fa-check"></i><b>9.1.3</b> Estimating a Mean and Predicting a New Observation @ <span class="math inline">\(X=X^*\)</span></a></li>
<li class="chapter" data-level="9.1.4" data-path="regression-models.html"><a href="regression-models.html#analysis-of-variance"><i class="fa fa-check"></i><b>9.1.4</b> Analysis of Variance</a></li>
<li class="chapter" data-level="9.1.5" data-path="regression-models.html"><a href="regression-models.html#correlation"><i class="fa fa-check"></i><b>9.1.5</b> Correlation</a></li>
</ul></li>
<li class="chapter" data-level="9.2" data-path="regression-models.html"><a href="regression-models.html#multiple-linear-regression"><i class="fa fa-check"></i><b>9.2</b> Multiple Linear Regression</a>
<ul>
<li class="chapter" data-level="9.2.1" data-path="regression-models.html"><a href="regression-models.html#testing-and-estimation-for-partial-regression-coefficients"><i class="fa fa-check"></i><b>9.2.1</b> Testing and Estimation for Partial Regression Coefficients</a></li>
<li class="chapter" data-level="9.2.2" data-path="regression-models.html"><a href="regression-models.html#analysis-of-variance-1"><i class="fa fa-check"></i><b>9.2.2</b> Analysis of Variance</a></li>
<li class="chapter" data-level="9.2.3" data-path="regression-models.html"><a href="regression-models.html#testing-a-subset-of-betas-0"><i class="fa fa-check"></i><b>9.2.3</b> Testing a Subset of <span class="math inline">\(\beta^s = 0\)</span></a></li>
<li class="chapter" data-level="9.2.4" data-path="regression-models.html"><a href="regression-models.html#models-with-categorical-qualitative-predictors"><i class="fa fa-check"></i><b>9.2.4</b> Models With Categorical (Qualitative) Predictors</a></li>
<li class="chapter" data-level="9.2.5" data-path="regression-models.html"><a href="regression-models.html#models-with-interaction-terms"><i class="fa fa-check"></i><b>9.2.5</b> Models With Interaction Terms</a></li>
</ul></li>
<li class="chapter" data-level="9.3" data-path="regression-models.html"><a href="regression-models.html#logistic-regression"><i class="fa fa-check"></i><b>9.3</b> Logistic Regression</a></li>
</ul></li>
<li class="divider"></li>
<li><a href="https://github.com/rstudio/bookdown" target="blank">Published with bookdown</a></li>

</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">Statistics and the Physical World</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="regression-models" class="section level1 hasAnchor" number="9">
<h1><span class="header-section-number">Chapter 9</span> Regression Models<a href="regression-models.html#regression-models" class="anchor-section" aria-label="Anchor link to header"></a></h1>
<p>Linear regression is used when there is a numeric response variable and numeric (and possibly categorical)
predictor (explanatory) variable(s). The mean of the response variable is to be related
to the predictor(s) with random error terms typically assumed to be independent and normally distributed
with constant variance. The fitting of linear regression models is very flexible, allowing for
fitting curvature, categorical predictors, and interactions between factors.</p>
<p>Logistic Regression is used when the outcome is binary, and there are one or more numeric (or possibly categorical)
predictor variable(s). These models are used to determine whether the probability that the outcome of interest is associated with
the predictor variable(s).</p>
<div id="simple-linear-regression" class="section level2 hasAnchor" number="9.1">
<h2><span class="header-section-number">9.1</span> Simple Linear Regression<a href="regression-models.html#simple-linear-regression" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>When there is a single numeric predictor, the model is referred to as <strong>Simple Regression</strong>. The response
variable is denoted as <span class="math inline">\(Y\)</span> and the predictor variable is denoted as <span class="math inline">\(X\)</span>. The model is written as follows.</p>
<p><span class="math display">\[  Y = \beta_0 + \beta_1 X + \epsilon  \qquad \qquad \epsilon \sim N(0,\sigma) \mbox{ independent } \]</span></p>
<p>Here <span class="math inline">\(\beta_0\)</span> is the intercept (mean of <span class="math inline">\(Y\)</span> when <span class="math inline">\(X\)</span>=0) and <span class="math inline">\(\beta_1\)</span> is the slope (the change
in the mean of <span class="math inline">\(Y\)</span> when <span class="math inline">\(X\)</span> increases by 1 unit). Of primary concern is whether <span class="math inline">\(\beta_1=0\)</span>, which
implies the mean of <span class="math inline">\(Y\)</span> is constant (<span class="math inline">\(\beta_0\)</span>), and thus <span class="math inline">\(Y\)</span> and <span class="math inline">\(X\)</span> are not associated.</p>
<div id="estimation-of-model-parameters" class="section level3 hasAnchor" number="9.1.1">
<h3><span class="header-section-number">9.1.1</span> Estimation of Model Parameters<a href="regression-models.html#estimation-of-model-parameters" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>A sample of pairs <span class="math inline">\((X_i,Y_i) \quad i=1, \ldots,n\)</span> is observed. The goal is to choose estimators
of <span class="math inline">\(\beta_0\)</span> and <span class="math inline">\(\beta_1\)</span> that minimize the error sum of squares: <span class="math inline">\(Q=\sum_{i=1}^n \epsilon_i^2\)</span>. The
resulting <strong>ordinary least squares</strong> estimators are given below (the formulas are derived making use of calculus).</p>
<p><span class="math display">\[ Y_i = \beta_0 + \beta_1 X_i + \epsilon_i \quad i=1,\ldots,n \qquad \epsilon_i=Y_i-\left(\beta_0 + \beta_1X_i\right) \]</span></p>
<p><span class="math display">\[ \hat{\beta}_1 = \frac{\sum(X-\overline{X})(Y-\overline{Y})}{\sum(X-\overline{X})^2}  \qquad \qquad  
\hat{\beta}_0 = \overline{Y} - \hat{\beta}_1 \overline{X}  \]</span></p>
<p>It helps to use the following short-hand notation.</p>
<p><span class="math display">\[ SS_{XY}=\sum(X-\overline{X})(Y-\overline{Y}) \quad
SS_{XX}=\sum(X-\overline{X})^2 \quad
SS_{YY}=\sum(Y-\overline{Y})^2 \]</span></p>
<p>Once estimates have been computed, <strong>fitted values</strong> and <strong>residuals</strong> are obtained for each observation.
The <strong>error sum of squares (SSE)</strong> is obtained as the sum of the squared residuals from the regression fit.</p>
<p><span class="math display">\[ \mbox{Fitted Values: } \hat{y}_i = \hat{\beta}_0 + \hat{\beta}_1 X_i \qquad \qquad  \mbox{Residuals: } e_i = Y_i-\hat{y}_i \]</span>
<span class="math display">\[ SSE=\sum(Y-\hat{Y})^2=SS_{YY}-\hat{\beta}_1^2SS_{XX}^2  \]</span></p>
<p>The
(unbiased) estimator of the error variance <span class="math inline">\(\sigma^2\)</span> is <span class="math inline">\(s^2=MSE=\frac{SSE}{n-2}\)</span>, where
<span class="math inline">\(MSE\)</span> is the <strong>Mean Square Error</strong>. The subtraction of
2 can be thought of as the fact two parameters have been estimated: <span class="math inline">\(\beta_0\)</span> and <span class="math inline">\(\beta_1\)</span>.</p>
<p>The estimators <span class="math inline">\(\hat{\beta}_1\)</span> and <span class="math inline">\(\hat{\beta}_0\)</span> are linear functions of <span class="math inline">\(Y_1, \ldots,Y_n\)</span> and thus using basic rules
of mathematical statistics, their sampling distributions are as follow, assuming the error terms are normal, independent,
with constant variance.</p>
<p><span class="math display">\[ \hat{\beta}_1 \sim N\left(\beta_1,\sqrt{\frac{\sigma^2}{SS_{XX}}}\right)     \qquad
   \hat{\beta}_0 \sim N\left(\beta_0,\sqrt{\sigma^2\left[\frac{1}{n}+
   \frac{\overline{X}^2}{SS_{XX}}\right]} \right)  \]</span></p>
<p>The estimated standard errors are the
standard error with the unknown <span class="math inline">\(\sigma^2\)</span> replaced by <span class="math inline">\(MSE\)</span>.</p>
<p><span class="math display">\[   \widehat{SE}\{\hat{\beta}_1\} = \sqrt{\frac{MSE}{SS_{XX}}} \qquad   \widehat{SE}\{\hat{\beta}_0\} = \sqrt{MSE\left[\frac{1}{n}+\frac{\overline{X}^2}{SS_{XX}}\right]}  \]</span></p>
<p><strong>Example 9.1: Aging of Textiles by Cysteic Acid Levels</strong></p>
<p>A study was conducted relating the age of wool carpets and threads <span class="math inline">\(Y\)</span> to their cysteic acid levels <span class="math inline">\(X\)</span> <span class="citation">(<a href="#ref-csapo_1995">Csapo et al. 1995</a>)</span>.
The sample consisted of <span class="math inline">\(n=23\)</span> specimens with both known ages and cysteic acid levels.
A plot of the data is given in Figure <a href="regression-models.html#fig:cysteic1">9.1</a> and calculations used to fit the linear regression are given in Table <a href="regression-models.html#tab:cysteic1">9.1</a>.</p>
<pre><code>##   sample_id  age cys_acid  cys  met  tyr
## 1      1.1. 1750     4.39 0.97 0.00 0.00
## 2      1.2. 1600     4.30 1.03 0.00 0.00
## 3      1.3. 1600     4.27 1.21 0.02 0.15
## 4      1.4. 1600     4.33 1.10 0.02 0.20
## 5      1.5. 1600     4.01 1.19 0.01 0.20
## 6      1.6. 1550     3.99 1.22 0.03 0.30</code></pre>
<pre><code>##    sample_id age cys_acid  cys  met  tyr
## 20     2.22. 170     1.19 4.15 0.33 2.37
## 21     1.17. 140     1.22 4.24 0.38 2.85
## 22     2.23. 128     1.03 4.20 0.40 2.59
## 23     2.24. 120     0.88 5.19 0.39 2.83
## 24     1.18.  NA     1.92 3.24 0.24 1.99
## 25     2.25.  NA     1.44 3.91 0.34 2.38</code></pre>
<table>
<caption><span id="tab:cysteic1">Table 9.1: </span>Linear regression of age of wool threads and carpets on cysteic acid levels</caption>
<colgroup>
<col width="2%" />
<col width="9%" />
<col width="9%" />
<col width="9%" />
<col width="9%" />
<col width="9%" />
<col width="15%" />
<col width="15%" />
<col width="8%" />
<col width="7%" />
</colgroup>
<thead>
<tr class="header">
<th align="left"></th>
<th align="right"><span class="math inline">\(\bar{Y}\)</span></th>
<th align="right"><span class="math inline">\(\bar{X}\)</span></th>
<th align="right"><span class="math inline">\(SS_{XY}\)</span></th>
<th align="right"><span class="math inline">\(SS_{XX}\)</span></th>
<th align="right"><span class="math inline">\(SS_{YY}\)</span></th>
<th align="right"><span class="math inline">\(\hat{\beta}_1\)</span></th>
<th align="right"><span class="math inline">\(\hat{\beta}_0\)</span></th>
<th align="right"><span class="math inline">\(SSE\)</span></th>
<th align="right"><span class="math inline">\(s^2\)</span></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left"></td>
<td align="right">1017.739</td>
<td align="right">2.895</td>
<td align="right">18550.79</td>
<td align="right">39.697</td>
<td align="right">8733546</td>
<td align="right">467.31</td>
<td align="right">-335.225</td>
<td align="right">64576.89</td>
<td align="right">3075.09</td>
</tr>
</tbody>
</table>
<div class="figure" style="text-align: center"><span style="display:block;" id="fig:cysteic1"></span>
<img src="STA2170bookdownproj_files/figure-html/cysteic1-1.png" alt="Age of wool threads and carpets (Y) and cysteic acid levels (X) for n=23 specimens and linear regression line" width="80%" />
<p class="caption">
Figure 9.1: Age of wool threads and carpets (Y) and cysteic acid levels (X) for n=23 specimens and linear regression line
</p>
</div>
<p>Calculations for the linear regression are given below.</p>
<p><span class="math display">\[ n=23 \qquad \overline{X}=2.895 \qquad \overline{Y}=1017.739 \]</span>
<span class="math display">\[ SS_{XX}=39.697 \qquad SS_{YY}=8733546 \qquad SS_{XY}=18550.79 \]</span></p>
<p><span class="math display">\[ \hat{\beta}_1 = \frac{18550.79}{39.697} = 467.31 \qquad \qquad \hat{\beta}_0 = 1017.739 - 467.31(2.895) = -335.225 \]</span>
<span class="math display">\[ SSE=8733546 - \frac{(18550.79)^2}{(39.697)} = 64576.89
\qquad\qquad   s^2=MSE=\frac{SSE}{n-2}=\frac{64576.89}{23-2} = 3075.09\]</span></p>
<p><span class="math display">\[   \widehat{SE}\{\hat{\beta}_1\} = \sqrt{\frac{3075.09}{39.697}} = 8.801 \qquad   \widehat{SE}\{\hat{\beta}_0\} = \sqrt{3075.09\left[\frac{1}{23}+\frac{2.895^2}{39.697}\right]}=
27.981  \]</span></p>
<p>Results from fitting the regression model with the <strong>lm</strong> function in R is given in the following R code chunk.</p>
<div class="sourceCode" id="cb98"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb98-1"><a href="regression-models.html#cb98-1" tabindex="-1"></a><span class="do">## Continuation of cysteic1</span></span>
<span id="cb98-2"><a href="regression-models.html#cb98-2" tabindex="-1"></a></span>
<span id="cb98-3"><a href="regression-models.html#cb98-3" tabindex="-1"></a>mod1 <span class="ot">&lt;-</span> <span class="fu">lm</span>(age <span class="sc">~</span> cys_acid, <span class="at">data=</span>wca23)</span>
<span id="cb98-4"><a href="regression-models.html#cb98-4" tabindex="-1"></a><span class="fu">summary</span>(mod1)</span></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = age ~ cys_acid, data = wca23)
## 
## Residuals:
##    Min     1Q Median     3Q    Max 
## -94.89 -48.05  18.38  31.87 100.10 
## 
## Coefficients:
##             Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept) -335.225     27.983  -11.98 7.51e-11 ***
## cys_acid     467.310      8.801   53.09  &lt; 2e-16 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 55.45 on 21 degrees of freedom
## Multiple R-squared:  0.9926, Adjusted R-squared:  0.9923 
## F-statistic:  2819 on 1 and 21 DF,  p-value: &lt; 2.2e-16</code></pre>
<div class="sourceCode" id="cb100"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb100-1"><a href="regression-models.html#cb100-1" tabindex="-1"></a><span class="fu">anova</span>(mod1)</span></code></pre></div>
<pre><code>## Analysis of Variance Table
## 
## Response: age
##           Df  Sum Sq Mean Sq F value    Pr(&gt;F)    
## cys_acid   1 8668970 8668970  2819.1 &lt; 2.2e-16 ***
## Residuals 21   64577    3075                      
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
<p><span class="math display">\[ \nabla   \]</span></p>
</div>
<div id="inference-regarding-beta_1-and-beta_0" class="section level3 hasAnchor" number="9.1.2">
<h3><span class="header-section-number">9.1.2</span> Inference Regarding <span class="math inline">\(\beta_1\)</span> and <span class="math inline">\(\beta_0\)</span><a href="regression-models.html#inference-regarding-beta_1-and-beta_0" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Primarily of interest are inferences regarding <span class="math inline">\(\beta_1\)</span>. Note that if <span class="math inline">\(\beta_1=0\)</span>, <span class="math inline">\(Y\)</span> and <span class="math inline">\(X\)</span> are not linearly associated.
We can test hypotheses and construct confidence intervals based on the estimate <span class="math inline">\(\beta_1\)</span> and
its estimated standard error. The <span class="math inline">\(t\)</span>-test is conducted as follows. Note that the null value <span class="math inline">\(\beta_{10}\)</span> is
almost always 0, and that software packages that report these tests always are treating <span class="math inline">\(\beta_{10}\)</span> as 0.</p>
<p><span class="math display">\[  H_0: \beta_1=\beta_{10}   \quad   H_A: \beta_1 \not= \beta_{10}   \quad   \mbox{TS: } t_{obs} = \frac{\hat{\beta}_1-\beta_{10}}{\widehat{SE}\{\hat{\beta}_1\}} \]</span>
<span class="math display">\[ \mbox{RR: } |t_{obs}| \geq t_{\alpha /2, n-2}  \qquad \qquad P= 2P\left(t_{n-2} \geq |t_{obs}|\right)  \]</span></p>
<p>One-sided tests use the same test statistic, but the Rejection Region and p-value are changed to reflect
the alternative hypothesis.</p>
<p><span class="math display">\[   H_A^+: \beta_1 &gt; \beta_{10}   
\qquad \mbox{RR: } t_{obs} \geq t_{\alpha, n-2}  \qquad P=P\left(t_{n-2} \geq t_{obs}\right)  \]</span></p>
<p><span class="math display">\[ H_A^-: \beta_1 &lt; \beta_{10}   
\qquad \mbox{RR: } t_{obs} \leq -t_{\alpha, n-2}  \qquad P=P\left(t_{n-2} \leq t_{obs}\right)  \]</span></p>
<p>A <span class="math inline">\((1-\alpha)100\%\)</span> confidence interval for <span class="math inline">\(\beta_1\)</span> is obtained as:</p>
<p><span class="math display">\[ \hat{\beta}_1  \pm t_{\alpha /2, n-2} \widehat{SE}\{\hat{\beta}_1\}    \]</span></p>
<p>Note that the confidence interval represents the values of <span class="math inline">\(\beta_{10}\)</span> for which the two-sided test:
<span class="math inline">\(H_0: \beta_1=\beta_{10}   \quad   H_A: \beta_1 \not= \beta_{10}\)</span> fails to reject the null hypothesis.</p>
<p>Inferences regarding <span class="math inline">\(\beta_0\)</span> are of less interest in practice, but can be conducted in analogous manner,
using the estimate <span class="math inline">\(\hat{\beta}_0\)</span> and its estimated standard error <span class="math inline">\(\widehat{SE}\{\hat{\beta}_0\}\)</span>.</p>
<p><strong>Example 9.2: Aging of Textiles by Cysteic Acid Levels</strong></p>
<p>Continuing with the wool aging data, a test of <span class="math inline">\(H_0:\beta_1=0\)</span>
and a 95% Confidence Interval for <span class="math inline">\(\beta_1\)</span> are obtained. WE use data from the output from R,
as opposed to our direct calculations, as they are based on more internal decimal places.</p>
<p><span class="math display">\[ H_0:\beta_1=0 \qquad H_A:\beta_1 \neq 0 \qquad \mbox{TS: } t_{obs}=\frac{467.310}{8.801}=53.09 \]</span>
<span class="math display">\[ \mbox{RR: } |t_{obs}|\geq 2.080 \qquad P\approx 0 \]</span></p>
<p><span class="math display">\[ 95\% \mbox{ CI for } \beta_1: 467.310 \pm 2.080(8.801) \equiv 467.310 \pm 18.306 \equiv (449.004,485.616) \]</span></p>
<p>There is strong evidence of an association between age and cysteic acid level.
We are confident that as cysteic acid level increases by 1 unit, age increases by between 450 and 485 years.</p>
<p>Similarly, inference regarding the intercept <span class="math inline">\(\beta_0\)</span>
can be made as well (although it is of less interest as no specimens cysteic acid=0).</p>
<p><span class="math display">\[ H_0:\beta_0=0 \qquad H_A:\beta_0 \neq 0 \qquad \mbox{TS: }  t_{obs}=\frac{-335.25}{27.983}=-11.98\]</span>
<span class="math display">\[ \mbox{RR: } |t_{obs}|\geq 2.080 \qquad P\approx 0 \]</span></p>
<p><span class="math display">\[ 95\% \mbox{ CI for } \beta_0: -335.25 \pm 2.080(27.983) \equiv -335.25 \pm 58.21 \equiv (-393.42,-277.03) \]</span>
The <span class="math inline">\(t\)</span>-tests and Confidence Intervals are obtained in the following R code chunk.</p>
<div class="sourceCode" id="cb102"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb102-1"><a href="regression-models.html#cb102-1" tabindex="-1"></a><span class="do">## Continuation of cysteic2</span></span>
<span id="cb102-2"><a href="regression-models.html#cb102-2" tabindex="-1"></a></span>
<span id="cb102-3"><a href="regression-models.html#cb102-3" tabindex="-1"></a>mod1 <span class="ot">&lt;-</span> <span class="fu">lm</span>(age <span class="sc">~</span> cys_acid, <span class="at">data=</span>wca23)</span>
<span id="cb102-4"><a href="regression-models.html#cb102-4" tabindex="-1"></a><span class="fu">summary</span>(mod1)</span></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = age ~ cys_acid, data = wca23)
## 
## Residuals:
##    Min     1Q Median     3Q    Max 
## -94.89 -48.05  18.38  31.87 100.10 
## 
## Coefficients:
##             Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept) -335.225     27.983  -11.98 7.51e-11 ***
## cys_acid     467.310      8.801   53.09  &lt; 2e-16 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 55.45 on 21 degrees of freedom
## Multiple R-squared:  0.9926, Adjusted R-squared:  0.9923 
## F-statistic:  2819 on 1 and 21 DF,  p-value: &lt; 2.2e-16</code></pre>
<div class="sourceCode" id="cb104"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb104-1"><a href="regression-models.html#cb104-1" tabindex="-1"></a><span class="fu">confint</span>(mod1)</span></code></pre></div>
<pre><code>##                 2.5 %    97.5 %
## (Intercept) -393.4178 -277.0318
## cys_acid     449.0065  485.6134</code></pre>
<p><span class="math display">\[ \nabla \]</span></p>
</div>
<div id="estimating-a-mean-and-predicting-a-new-observation-xx" class="section level3 hasAnchor" number="9.1.3">
<h3><span class="header-section-number">9.1.3</span> Estimating a Mean and Predicting a New Observation @ <span class="math inline">\(X=X^*\)</span><a href="regression-models.html#estimating-a-mean-and-predicting-a-new-observation-xx" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>There may be interest in estimating the mean response at a specific level <span class="math inline">\(X^*\)</span>.
The parameter of interest is <span class="math inline">\(\mu^*=\beta_0+\beta_1X^*\)</span>.
The point estimator,
standard error, and <span class="math inline">\((1-\alpha)100\%\)</span> Confidence Interval are given below.</p>
<p><span class="math display">\[  \hat{y}=
\hat{\beta}_0+\hat{\beta}_1X^* \qquad \widehat{SE}\left\{\hat{y}^*\right\}=\sqrt{MSE\left[\frac{1}{n}+\frac{\left(X^*-\overline{X}\right)^2}{SS_{XX}}\right]}  \]</span>
<span class="math display">\[ (1-\alpha)100\% \mbox{ CI }:  \hat{y}^* \pm t_{\alpha /2, n-2} \widehat{SE}\left\{\hat{y}^*\right\}  \]</span></p>
<p>To obtain a simultaneous <span class="math inline">\((1-\alpha)100\%\)</span> Confidence Interval for the entire regression line (not just a single point),
the Working-Hotelling method can be used.</p>
<p><span class="math display">\[ \hat{y}^* \pm \sqrt{2F_{\alpha ,2, n-2}} \hspace{0.05in} \widehat{SE}\left\{\hat{y}^*\right\}  \]</span></p>
<p>If the goal is to predict a new observation when <span class="math inline">\(X=X^*\)</span>, uncertainty with respect to estimating
the mean (as seen by the Confidence Interval above), and the random error for the new case (with standard deviation <span class="math inline">\(\sigma\)</span>) must be taken into account.
The point prediction is the same as for the mean. The prediction, standard error of prediction, and
<span class="math inline">\((1-\alpha)100\%\)</span> Prediction Interval are given below.</p>
<p><span class="math display">\[  \hat{y}^*_{\mbox{New}}=\hat{\beta}_0+\hat{\beta}_1X^* \qquad  \widehat{SE}\left\{\hat{y}^*_{\mbox{New}}\right\}=\sqrt{MSE\left[1+\frac{1}{n}+
\frac{\left(X^*-\overline{X}\right)^2}{SS_{XX}}\right]}
\]</span></p>
<p><span class="math display">\[  (1-\alpha)100\% \mbox{ PI }:  \hat{y}^*_{\mbox{New}} \pm t_{\alpha /2, n-2} \widehat{SE}\left\{\hat{y}^*_{\mbox{New}}\right\}  \]</span></p>
<p>Note that the Prediction Interval will tend to be much wider than the Confidence Interval for the mean.</p>
<p><strong>Example 9.3: Aging of Textiles by Cysteic Acid</strong></p>
<p>In the paper, the authors included two specimens of unknown age, but with known cysteic acid levels (1.92 and 1.44, respectively). We will contruct 95% Confidence Intervals individually (without a Bonferroni adjustment for simultaneous intervals). Then we will repeat for
Prediction Intervals for the individual specimens.</p>
<p>The predicted values are given below.</p>
<p><span class="math display">\[\hat{y}_1^*=-335.225+467.310(1.92)=562.01  \qquad
\hat{y}_2^*=-335.225+467.310(1.44)=337.70\]</span></p>
<p>The estimated standard error for the mean when <span class="math inline">\(X^*=1.92\)</span> is given below.</p>
<p><span class="math display">\[\widehat{SE}\left\{\hat{y}^*\right\}=\sqrt{3075\left[\frac{1}{23}+\frac{\left(1.92-2.895\right)^2}{39.697}\right]} = \sqrt{3075(0.0674)} = 14.40\]</span>
The estimated standard error for an individual specimen with <span class="math inline">\(X^*=1.92\)</span> is given below.</p>
<p><span class="math display">\[\widehat{SE}\left\{\hat{y}_{\mbox{New}}^*\right\}=\sqrt{3075\left[1+\frac{1}{23}+\frac{\left(1.92-2.895\right)^2}{39.697}\right]} = \sqrt{3075(1.0674)} = 57.29\]</span>
<span class="math display">\[ 95\% \mbox{ CI for mean: } \quad 562.01\pm2.080(14.40)\equiv 562.01\pm29.95\equiv(532.06,591.96)\]</span>
<span class="math display">\[ 95\% \mbox{ PI for individual: } \quad 562.01\pm2.080(57.29)\equiv 562.01\pm119.16\equiv(442.85,681.17)\]</span></p>
<p>A plot of the data, fitted equation, 95% Confidence and Prediction Intervals are given in
Figure <a href="regression-models.html#fig:cysteic4">9.2</a>. The R code chunk below uses the <strong>predict</strong> function to obtain
95% CI’s for them and 95% PI’s for the individual specimens for the cysteic acid levels corresponding to the two cases with unknown ages.</p>
<div class="figure" style="text-align: center"><span style="display:block;" id="fig:cysteic4"></span>
<img src="STA2170bookdownproj_files/figure-html/cysteic4-1.png" alt="Age of wool threads and carpets (Y) and cysteic acid levels (X): linear regression line, 95% Confidence and Prediction Bands" width="80%" />
<p class="caption">
Figure 9.2: Age of wool threads and carpets (Y) and cysteic acid levels (X): linear regression line, 95% Confidence and Prediction Bands
</p>
</div>
<div class="sourceCode" id="cb106"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb106-1"><a href="regression-models.html#cb106-1" tabindex="-1"></a>cys_acid.new <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="fl">1.92</span>, <span class="fl">1.44</span>)</span>
<span id="cb106-2"><a href="regression-models.html#cb106-2" tabindex="-1"></a><span class="fu">predict</span>(mod1, <span class="fu">list</span>(<span class="at">cys_acid=</span>cys_acid.new), <span class="at">int=</span><span class="st">&quot;c&quot;</span>)     <span class="do">## CI for mean</span></span></code></pre></div>
<pre><code>##        fit      lwr      upr
## 1 562.0103 532.0630 591.9576
## 2 337.7015 301.8174 373.5857</code></pre>
<div class="sourceCode" id="cb108"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb108-1"><a href="regression-models.html#cb108-1" tabindex="-1"></a><span class="fu">predict</span>(mod1, <span class="fu">list</span>(<span class="at">cys_acid=</span>cys_acid.new), <span class="at">int=</span><span class="st">&quot;p&quot;</span>)     <span class="do">## PI for individual</span></span></code></pre></div>
<pre><code>##        fit      lwr      upr
## 1 562.0103 442.8635 681.1572
## 2 337.7015 216.9257 458.4774</code></pre>
<p><span class="math display">\[ \nabla \]</span></p>
</div>
<div id="analysis-of-variance" class="section level3 hasAnchor" number="9.1.4">
<h3><span class="header-section-number">9.1.4</span> Analysis of Variance<a href="regression-models.html#analysis-of-variance" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>When there is no association between <span class="math inline">\(Y\)</span> and <span class="math inline">\(X\)</span> <span class="math inline">\((\beta_1=0)\)</span>, the best predictor of each observation
is <span class="math inline">\(\overline{Y} = \hat{\beta}_0\)</span> (in terms of minimizing sum of squares of prediction errors). In this case, the total
variation can be denoted as <span class="math inline">\(TSS=\sum(Y-\overline{Y})^2=SS_{YY}\)</span>, the <strong>Total Sum of Squares</strong>.</p>
<p>When there is an association between <span class="math inline">\(Y\)</span> and <span class="math inline">\(X\)</span> <span class="math inline">\(\left(\beta_1\neq 0\right)\)</span>, the best predictor of each observation
is <span class="math inline">\(\hat{y}_i = \hat{\beta}_0 + \hat{\beta}_1 X_i\)</span> (in terms of minimizing sum of squares of prediction errors). In this case, the error
variation can be denoted as <span class="math inline">\(SSE=\sum(Y-\hat{Y})^2\)</span>, the <strong>Error Sum of Squares</strong>.</p>
<p>The difference between <span class="math inline">\(TSS\)</span> and <span class="math inline">\(SSE\)</span> is the variation ``explained’’ by the regression of <span class="math inline">\(Y\)</span> on <span class="math inline">\(X\)</span> (as opposed
to having ignored <span class="math inline">\(X\)</span>). It represents the difference between the fitted values and the mean: <span class="math inline">\(SSR=\sum\left(\hat{Y}-\overline{Y}\right)^2\)</span> the
<strong>Regression Sum of Squares</strong>.</p>
<p><span class="math display">\[ TSS = SSE + SSR   \qquad  \qquad  \sum(Y-\overline{Y})^2 = \sum(Y-\hat{Y})^2 + \sum\left(\hat{Y}-\overline{Y}\right)^2   \]</span></p>
<p>A plot including the data <span class="math inline">\((Y)\)</span>, the horizontal line at the mean response <span class="math inline">\((\overline{Y})\)</span> and the fitted
equation is given in Figure <a href="regression-models.html#fig:cysteic6">9.3</a>. The sum of the squared vertical distances from the data <span class="math inline">\(Y_i\)</span> to <span class="math inline">\(\overline{Y}\)</span>
is the Total Sum of Squares <span class="math inline">\(TSS\)</span>. The sum of the squared vertical distances from <span class="math inline">\(Y_i\)</span> to
their fitted values <span class="math inline">\(\hat{Y}_i\)</span> is the Error Sum of Squares <span class="math inline">\(SSE\)</span>.
The sum of the squared vertical distances from <span class="math inline">\(\hat{Y}_i\)</span> to <span class="math inline">\(\overline{Y}\)</span> is the Regression Sum of Squares <span class="math inline">\(SSR\)</span>.</p>
<div class="figure" style="text-align: center"><span style="display:block;" id="fig:cysteic6"></span>
<img src="STA2170bookdownproj_files/figure-html/cysteic6-1.png" alt="Age of wool threads and carpets (Y) and cysteic acid levels (X): linear regression line and line at overall mean age" width="80%" />
<p class="caption">
Figure 9.3: Age of wool threads and carpets (Y) and cysteic acid levels (X): linear regression line and line at overall mean age
</p>
</div>
<p>Each sum of squares has a <strong>degrees of freedom</strong> associated with it. The <strong>Total Degrees of Freedom</strong> is
<span class="math inline">\(df_{\mbox{Total}}=n-1\)</span>. The <strong>Error Degrees of Freedom</strong> is <span class="math inline">\(df_{\mbox{Error}}=n-2\)</span> (for simple regression).
The <strong>Regression Degrees of Freedom</strong> is <span class="math inline">\(df_{\mbox{Regression}}=1\)</span> (for simple regression).</p>
<p><span class="math display">\[ df_{\mbox{Total}}= df_{\mbox{Error}} +  df_{\mbox{Regression}}   \qquad  n-1=n-2 +1   \]</span></p>
<p>The Error and Regression sums of squares have <strong>Mean Squares</strong>, which are the sum of squares divided by
their corresponding degrees of freedom: <span class="math inline">\(MSE=SSE/(n-2)\)</span> and <span class="math inline">\(MSR=SSR/1\)</span>. It can be shown that these
mean squares have the following <strong>Expected Values</strong>, average values in repeated sampling at the same
observed <span class="math inline">\(X\)</span> levels.</p>
<p><span class="math display">\[ E\{MSE\}=\sigma^2 \qquad \qquad  E\{MSR\}=\sigma^2 + \beta_1^2 \sum(X-\overline{X})^2   \]</span></p>
<p>Note that when <span class="math inline">\(\beta_1=0\)</span>, then <span class="math inline">\(E\{MSR\}=E\{MSE\}\)</span>, otherwise <span class="math inline">\(E\{MSR\}&gt;E\{MSE\}\)</span>. A second way of
testing whether <span class="math inline">\(\beta_1=0\)</span> is by the following <span class="math inline">\(F\)</span>-test.</p>
<p><span class="math display">\[  H_0: \beta_1=0   \qquad   H_A: \beta_1 \not= 0   \qquad   \mbox{TS: } F_{obs} = \frac{MSR}{MSE} \]</span>
<span class="math display">\[ \mbox{RR: } F_{obs} \geq F_{\alpha,1, n-2}  \qquad P=P\left(F_{1,n-2} \geq F_{obs}\right)  \]</span></p>
<p>The Analysis of Variance is typically set up in a table as in Table <a href="regression-models.html#tab:anovaslr">9.2</a>.</p>
<table>
<caption><span id="tab:anovaslr">Table 9.2: </span>Analysis of Variance for simple linear regression</caption>
<thead>
<tr class="header">
<th align="left"></th>
<th align="left">Source</th>
<th align="left"><span class="math inline">\(df\)</span></th>
<th align="left"><span class="math inline">\(SS\)</span></th>
<th align="left"><span class="math inline">\(MS\)</span></th>
<th align="left"><span class="math inline">\(F_{obs}\)</span></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left"></td>
<td align="left">Regression</td>
<td align="left">1</td>
<td align="left">SSR</td>
<td align="left">MSR=SSR/1</td>
<td align="left">F=MSR/MSE</td>
</tr>
<tr class="even">
<td align="left"></td>
<td align="left">Error</td>
<td align="left">n-2</td>
<td align="left">SSE</td>
<td align="left">MSE=SSE/(n-2)</td>
<td align="left"></td>
</tr>
<tr class="odd">
<td align="left"></td>
<td align="left">Total</td>
<td align="left">n-1</td>
<td align="left">TSS</td>
<td align="left"></td>
<td align="left"></td>
</tr>
</tbody>
</table>
<p>A measure often reported from a regression analysis is the <strong>Coefficient of Determination</strong> or <strong><span class="math inline">\(r^2\)</span></strong>.
This represents the variation in <span class="math inline">\(Y\)</span> “explained” by <span class="math inline">\(X\)</span>, divided by the total variation in <span class="math inline">\(Y\)</span>.</p>
<p><span class="math display">\[ r^2=\frac{\sum\left(\hat{Y}-\overline{Y}\right)^2}{\sum(Y-\overline{Y})^2}=\frac{SSR}{TSS}=1-\frac{SSE}{TSS} \qquad 0 \leq r^2 \leq 1 \]</span></p>
<p>The interpretation of <span class="math inline">\(r^2\)</span> is the proportion of variation in <span class="math inline">\(Y\)</span> that is “explained” by <span class="math inline">\(X\)</span>,
and is often reported as a percentage (<span class="math inline">\(100r^2\)</span>).</p>
<p><strong>Example 9.4: Aging of Textiles by Cysteic Acid</strong></p>
<p>Continuing with the aging of textiles study, the Analysis of Variance
and <span class="math inline">\(F\)</span>-test are given in the following R code chunk. Note that the Total Sum of Squares and Error Sum of Squares
were computed in Example 9.1. The Regression Sum of Squares is the difference <span class="math inline">\(SSR=TSS-SSE=8733546-64577=8668969\)</span>. We obtain the summary and Analysis of Variance from the
model fit using the <strong>lm</strong> function in R, with the <strong>summary</strong> and <strong>anova</strong> commands.</p>
<div class="sourceCode" id="cb110"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb110-1"><a href="regression-models.html#cb110-1" tabindex="-1"></a>mod2 <span class="ot">&lt;-</span> <span class="fu">lm</span>(age <span class="sc">~</span> cys_acid, <span class="at">data=</span>wca23)</span>
<span id="cb110-2"><a href="regression-models.html#cb110-2" tabindex="-1"></a><span class="fu">summary</span>(mod2)</span></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = age ~ cys_acid, data = wca23)
## 
## Residuals:
##    Min     1Q Median     3Q    Max 
## -94.89 -48.05  18.38  31.87 100.10 
## 
## Coefficients:
##             Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept) -335.225     27.983  -11.98 7.51e-11 ***
## cys_acid     467.310      8.801   53.09  &lt; 2e-16 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 55.45 on 21 degrees of freedom
## Multiple R-squared:  0.9926, Adjusted R-squared:  0.9923 
## F-statistic:  2819 on 1 and 21 DF,  p-value: &lt; 2.2e-16</code></pre>
<div class="sourceCode" id="cb112"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb112-1"><a href="regression-models.html#cb112-1" tabindex="-1"></a><span class="fu">anova</span>(mod2)</span></code></pre></div>
<pre><code>## Analysis of Variance Table
## 
## Response: age
##           Df  Sum Sq Mean Sq F value    Pr(&gt;F)    
## cys_acid   1 8668970 8668970  2819.1 &lt; 2.2e-16 ***
## Residuals 21   64577    3075                      
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
<p>The coefficient of determination, <span class="math inline">\(r^2\)</span>, is 8668970/8733546=0.9926. Almost all of the variation in age is
“explained” by cysteic acid level. The <strong>summary</strong> contains the following values.</p>
<ul>
<li>Regression coefficients, standard errors, <span class="math inline">\(t\)</span>-statistics and p-values</li>
<li>Residual standard error (estimate of the standard deviation of the error terms) and its degrees of freedom</li>
<li><span class="math inline">\(r^2\)</span> - Proportion of variation in <span class="math inline">\(Y\)</span> “explained” by the predictor variable</li>
<li>Adjusted <span class="math inline">\(r^2\)</span> - An adjustment that penalizes when extra predictors are not improving model fit</li>
<li><span class="math inline">\(F\)</span>-statistic for testing whether <span class="math inline">\(\beta_1=0\)</span>, with its degrees of freedom and p-value.</li>
</ul>
<p>The <strong>anova</strong> command gives the Analysis of Variance Table.</p>
<p><span class="math display">\[ \nabla \]</span></p>
</div>
<div id="correlation" class="section level3 hasAnchor" number="9.1.5">
<h3><span class="header-section-number">9.1.5</span> Correlation<a href="regression-models.html#correlation" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>The regression coefficient <span class="math inline">\(\beta_1\)</span> depends on the units of <span class="math inline">\(Y\)</span> and <span class="math inline">\(X\)</span>. It also depends on
which variable is the dependent variable and which is the independent variable. A second widely
reported measure is the <strong>Pearson Product Moment Coefficient of Correlation</strong>. It is
invariant to linear transformations of <span class="math inline">\(Y\)</span> and <span class="math inline">\(X\)</span>, and does not distinguish which is the
dependent and which is the independent variable. This makes it a widely reported measure when
researchers are interested in how two random variables vary together in a population. The population
correlation coefficient is labeled <span class="math inline">\(\rho\)</span>, and the sample correlation is labeled <span class="math inline">\(r\)</span>, and its
formula is given below.</p>
<p><span class="math display">\[ r = \frac{SS_{XY}}{\sqrt{SS_{XX} SS_{YY}}}= \left(\frac{s_X}{s_Y}\right) \hat{\beta}_1  \]</span></p>
<p>where <span class="math inline">\(s_X\)</span> and <span class="math inline">\(s_Y\)</span> are the standard deviations of <span class="math inline">\(X\)</span> and <span class="math inline">\(Y\)</span>, respectively. While
<span class="math inline">\(\hat{\beta}_1\)</span> can take on any value, <span class="math inline">\(r\)</span> lies between <span class="math inline">\(-1\)</span> and <span class="math inline">\(+1\)</span>, taking on the extreme values
if all of the points fall on a straight line. The test of whether <span class="math inline">\(\rho=0\)</span> is mathematically
equivalent to the <span class="math inline">\(t\)</span>-test for testing whether <span class="math inline">\(\beta_1=0\)</span>. The 2-sided test is given below.</p>
<p><span class="math display">\[  H_0: \rho=0   \qquad   H_A: \rho \not= 0   \qquad  \mbox{TS: } t_{obs} = \frac{r}{\sqrt{\frac{1-r^2}{n-2}}}\]</span>
<span class="math display">\[\mbox{RR: } |t_{obs}| \geq t_{\alpha /2, n-2}  \qquad P= 2P(t_{n-2} \geq |t_{obs}|)  \]</span></p>
<p>To construct a large-sample confidence interval, <strong>Fisher’s <span class="math inline">\(z\)</span> transform</strong> can be used to make the transformed <span class="math inline">\(r\)</span> to have
a sampling distribution that is<br />
approximately normal. A confidence interval is obtained on the transformed correlation,
then “back transformed” to the end points in terms of <span class="math inline">\(\rho\)</span>.</p>
<p><span class="math display">\[ z&#39;=\frac{1}{2}\ln\left(\frac{1+r}{1-r}\right) \qquad  (1-\alpha)100\% \mbox{ CI for }
\frac{1}{2}\ln\left(\frac{1+\rho}{1-\rho}\right): \quad z&#39; \pm z_{\alpha/2}\sqrt{\frac{1}{n-3}}  \]</span></p>
<p>Labeling the endpoints of the Confidence Interval as <span class="math inline">\((a,b)\)</span>, the Confidence Interval for <span class="math inline">\(\rho\)</span> is computed as follows.</p>
<p><span class="math display">\[ (1-\alpha)100\% \mbox{ Confidence
Interval for } \rho: \left(\frac{e^{2a}-1}{e^{2a}+1},\frac{e^{2b}-1}{e^{2b}+1}\right)   \]</span></p>
<p><strong>Example 9.5: Aging of Textiles by Cysteic Acid</strong></p>
<p>Continuing with the textile aging study, the sample correlation, a test of whether <span class="math inline">\(\rho=0\)</span>,
and a 95% Confidence Interval for <span class="math inline">\(\rho\)</span> are computed below.</p>
<p><span class="math display">\[ r=\frac{18551}{\sqrt{39.697(8733546)}}=0.9963   \qquad \qquad t_{obs}=\frac{0.9963}{\sqrt{\frac{1-0.9963^2}{23-2}}}=53.17 \]</span>
<span class="math display">\[ z&#39;=\frac{1}{2}\ln\left(\frac{1+0.9963}{1-0.9963}\right)=3.1454 \quad 3.1454 \pm 1.96 \sqrt{\frac{1}{23-3}} \equiv 3.1454 \pm 0.4383 \equiv
(2.7071,3.5837) \]</span>
<span class="math display">\[ \Rightarrow \quad 95\% \mbox{ CI for } \rho:
\left(\frac{e^{2(2.7071)}-1}{e^{2(2.7071)}+1},\frac{e^{2(3.5837)}-1}{e^{2(3.5837)}+1}\right)  \equiv \left(\frac{223.57}{225.57},\frac{1295.47}{1297.47}\right)
\equiv (.9911,.9985) \]</span></p>
<p>The following R code chunk computes the estimate, <span class="math inline">\(t\)</span>-test, and 95% Confidence Interval directly.</p>
<div class="sourceCode" id="cb114"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb114-1"><a href="regression-models.html#cb114-1" tabindex="-1"></a><span class="fu">cor.test</span>(wca23<span class="sc">$</span>age, wca23<span class="sc">$</span>cys_acid)</span></code></pre></div>
<pre><code>## 
##  Pearson&#39;s product-moment correlation
## 
## data:  wca23$age and wca23$cys_acid
## t = 53.095, df = 21, p-value &lt; 2.2e-16
## alternative hypothesis: true correlation is not equal to 0
## 95 percent confidence interval:
##  0.9911243 0.9984567
## sample estimates:
##       cor 
## 0.9962961</code></pre>
<p><span class="math display">\[ \nabla  \]</span></p>
</div>
</div>
<div id="multiple-linear-regression" class="section level2 hasAnchor" number="9.2">
<h2><span class="header-section-number">9.2</span> Multiple Linear Regression<a href="regression-models.html#multiple-linear-regression" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>When there is more than one predictor variable, the model generalizes to multiple linear regression. The calculations
become more complex, but conceptually, the ideas remain the same. We will use the notation of <span class="math inline">\(p\)</span> as the number
of predictors, and <span class="math inline">\(p&#39;=p+1\)</span> as the number of regression coefficients in the model (including the intercept).
The model can be written as follows with the same assumptions about the errors as in simple regression.</p>
<p><span class="math display">\[  Y = \beta_0 + \beta_1 X_1 + \cdots + \beta_p X_p + \epsilon  \qquad \qquad \epsilon \sim N(0,\sigma) \mbox{ independent } \]</span></p>
<p>Least squares (and maximum likelihood) estimates <span class="math inline">\(\hat{\beta}_0,\hat{\beta}_1,\ldots,\hat{\beta}_p\)</span> minimize the error sum of squares.
The fitted values, residuals, and error sum of squares are given below.</p>
<p><span class="math display">\[ \hat{Y}_i = \hat{\beta}_0 + \hat{\beta}_1X_{i1} + \cdots \hat{\beta}_pX_{ip}   \qquad  e_i = Y_i -\hat{Y}_i  \qquad SSE=\sum_{i=1}^n e_i^2 \]</span></p>
<p>The degrees of freedom for error are now <span class="math inline">\(n-p&#39;=n-(p+1)\)</span>, as the model estimates <span class="math inline">\(p&#39;=p+1\)</span> parameters. The degrees of freedom for
regression is <span class="math inline">\(p\)</span>.</p>
<p>In the multiple linear regression model, <span class="math inline">\(\beta_j\)</span> represents the change in <span class="math inline">\(E\{Y\}\)</span> when <span class="math inline">\(X_j\)</span> increases by 1 unit,
with all other predictor variables being held constant. It is referred to as the <strong>partial regression coefficient</strong>.</p>
<div id="testing-and-estimation-for-partial-regression-coefficients" class="section level3 hasAnchor" number="9.2.1">
<h3><span class="header-section-number">9.2.1</span> Testing and Estimation for Partial Regression Coefficients<a href="regression-models.html#testing-and-estimation-for-partial-regression-coefficients" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Once the model is fit, for each predictor variable,
the estimated regression coefficient,
its estimated standard error, <span class="math inline">\(t\)</span>-statistic and confidence interval are obtained.
Technically, the estimated variance-covariance matrix for the vector of
regression coefficients is computed, with the standard errors being the square root
of the variances of the individual coefficients.</p>
<p>To test whether <span class="math inline">\(Y\)</span> is associated with <span class="math inline">\(X_j\)</span>, after controlling for the remaining <span class="math inline">\(p-1\)</span> predictors, the test is
whether <span class="math inline">\(\beta_j=0\)</span>. This is equivalent to the <span class="math inline">\(t\)</span>-test from simple regression (in general, the test can be whether a regression
coefficient is any specific number, although software packages are testing whether it is 0).</p>
<p><span class="math display">\[  H_0: \beta_j=\beta_{j0}   \qquad   H_A: \beta_j \not= \beta_{j0}   \qquad   \mbox{TS: } t_{obs} = \frac{\hat{\beta}_j-\beta_{j0}}{\widehat{SE}\{\hat{\beta}_j\}}  \]</span>
<span class="math display">\[  \mbox{RR: } |t_{obs}| \geq t_{\alpha /2, n-p&#39;}  \qquad P=2P(t_{n-p&#39;} \geq |t_{obs}|)  \]</span></p>
<p>One-sided tests make the same adjustments as in simple linear regression.</p>
<p><span class="math display">\[   H_A^+: \beta_j &gt; \beta_{j0}   
\qquad \mbox{RR: } t_{obs} \geq t_{\alpha, n-p&#39;}  \qquad P=P(t_{n-p&#39;} \geq t_{obs})  \]</span></p>
<p><span class="math display">\[ H_A^-: \beta_j &lt; \beta_{j0}   
\qquad \mbox{RR: } t_{obs} \leq -t_{\alpha, n-p&#39;}  \qquad P=P(t_{n-p&#39;} \leq t_{obs})  \]</span></p>
<p>A <span class="math inline">\((1-\alpha)100\%\)</span> confidence interval for <span class="math inline">\(\beta_j\)</span> is obtained as:</p>
<p><span class="math display">\[ \hat{\beta}_j  \pm t_{\alpha /2, n-p&#39;} \widehat{SE}\{\hat{\beta}_j\}  \]</span></p>
<p>Note that the confidence interval represents the values of <span class="math inline">\(\beta_{j0}\)</span> for which the two-sided test:
<span class="math inline">\(H_0: \beta_j=\beta_{j0}   \quad   H_A: \beta_j \not= \beta_{j0}\)</span> fails to reject the null hypothesis.</p>
<p><strong>Example 9.6: How Stature (Height) Relates to Hand and Foot Length among Females</strong></p>
<p>A regression model was fit, relating stature (<span class="math inline">\(Y\)</span>, height, in mm) to hand length (<span class="math inline">\(X_1\)</span>, mm) and foot length (<span class="math inline">\(X_2\)</span>, mm) for a sample
of <span class="math inline">\(n=75\)</span> female adult Turks <span class="citation">(<a href="#ref-sanli_2005">Sanli et al. 2015</a>)</span>.
The data have been simulated to match means, standard deviations, and bivariate correlations.
A matrix plot of the variables is given in Figure <a href="regression-models.html#fig:staturef1">9.4</a>.
The model, fitted equation, Error sum of squares and mean square are given below <span class="math inline">\((n=75, p&#39;=2+1=3)\)</span>.</p>
<p><span class="math display">\[ Y_i = \beta_0 + \beta_1X_{i1} + \beta_2 X_{i2} + \epsilon_i \quad  \hat{y}_i = 743.970 + 2.375X_1 + 1.727 X_2 \]</span>
<span class="math display">\[ SSE=68924.42 \qquad MSE=\frac{68924.42}{75-3}=957.284  \]</span></p>
<p>The estimated standard errors are 0.486 for <span class="math inline">\(\hat{\beta}_1\)</span> and 0.375 for <span class="math inline">\(\hat{\beta}_2\)</span>, respectively. The <span class="math inline">\(t\)</span>-tests and 95% Confidence Intervals for <span class="math inline">\(\beta_1\)</span> and
<span class="math inline">\(\beta_2\)</span> are given below.</p>
<p><span class="math display">\[ \mbox{Hand: } \quad H_0:\beta_1=0 \qquad H_A:\beta_1\neq 0\qquad \mbox{TS: } t_{obs}=\frac{2.375}{0.486}=4.89 \]</span>
<span class="math display">\[ \mbox{RR: } |t_{obs}|\geq t_{.025,72}=1.993 \qquad
P=P\left(t_{72} \geq 5.63\right) \approx 0 \]</span></p>
<p><span class="math display">\[ \mbox{Foot: } \quad H_0:\beta_2=0 \qquad H_A:\beta_2\neq 0\qquad \mbox{TS: } t_{obs}=\frac{1.727}{0.375}=4.61 \]</span>
<span class="math display">\[ \mbox{RR: } |t_{obs}|\geq t_{.025,72}=1.993 \quad
P=P\left(t_{72} \geq 4.61\right) \approx 0 \]</span></p>
<p><span class="math display">\[ 95\% \mbox{ CI for } \beta_1: \qquad  2.375 \pm 1.993(0.486) \equiv 2.375\pm 0.969 \equiv (1.406,3.344) \]</span>
<span class="math display">\[ 95\% \mbox{ CI for } \beta_2:  \qquad 1.727 \pm 1.993(0.375) \equiv 1.727\pm 0.747 \equiv (0.980,2.474)   \]</span></p>
<p>The estimated regression coefficients, standard errors, <span class="math inline">\(t\)</span>-statistics, p-values, and 95%
Confidence Intervals are obtained in the following R code chunk.
After controlling for foot length, hand length is positively associated with height, and vice versa.</p>
<div class="figure" style="text-align: center"><span style="display:block;" id="fig:staturef1"></span>
<img src="STA2170bookdownproj_files/figure-html/staturef1-1.png" alt="Heights, Hand Lengths and Foot Lengths among a Sample of 75 Adult Female Turks" width="80%" />
<p class="caption">
Figure 9.4: Heights, Hand Lengths and Foot Lengths among a Sample of 75 Adult Female Turks
</p>
</div>
<pre><code>## 
## Call:
## lm(formula = height ~ handLen + footLen, data = shf.f)
## 
## Residuals:
##      Min       1Q   Median       3Q      Max 
## -130.696  -10.662    2.624   11.804   88.218 
## 
## Coefficients:
##             Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept) 743.6072    79.7423   9.325 5.20e-14 ***
## handLen       2.3766     0.4858   4.892 5.89e-06 ***
## footLen       1.7271     0.3743   4.614 1.68e-05 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 30.93 on 72 degrees of freedom
## Multiple R-squared:  0.6162, Adjusted R-squared:  0.6055 
## F-statistic: 57.79 on 2 and 72 DF,  p-value: 1.068e-15</code></pre>
<pre><code>##                   2.5 %     97.5 %
## (Intercept) 584.6437862 902.570640
## handLen       1.4082022   3.345094
## footLen       0.9809355   2.473189</code></pre>
<p><span class="math display">\[ \nabla   \]</span></p>
</div>
<div id="analysis-of-variance-1" class="section level3 hasAnchor" number="9.2.2">
<h3><span class="header-section-number">9.2.2</span> Analysis of Variance<a href="regression-models.html#analysis-of-variance-1" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>When there is no association between <span class="math inline">\(Y\)</span> and <span class="math inline">\(X_1,\ldots,X_p\)</span> <span class="math inline">\((\beta_1=\cdots =\beta_p=0)\)</span>, the best predictor of each observation
is <span class="math inline">\(\overline{Y} = \hat{\beta}_0\)</span> (in terms of minimizing sum of squares of prediction errors). In this case, the total
variation can be denoted as <span class="math inline">\(TSS=\sum(Y-\overline{Y})^2\)</span>, the <strong>Total Sum of Squares</strong>, just as with simple regression.</p>
<p>When there is an association between <span class="math inline">\(Y\)</span> and at least one of <span class="math inline">\(X_1,\ldots , X_p\)</span> (not all <span class="math inline">\(\beta_i = 0\)</span>), the best predictor of each observation
is <span class="math inline">\(\hat{y}_i = \hat{\beta}_0 + \hat{\beta}_1 X_{i1} + \cdots + \hat{\beta}_pX_{ip}\)</span> (in terms of minimizing the sum of squares of prediction errors). In this case, the error
variation can be denoted as <span class="math inline">\(SSE=\sum(Y-\hat{Y})^2\)</span>, the <strong>Error Sum of Squares</strong>.</p>
<p>The difference between <span class="math inline">\(TSS\)</span> and <span class="math inline">\(SSE\)</span> is the variation “explained” by the regression of <span class="math inline">\(Y\)</span> on <span class="math inline">\(X_1,\ldots , X_p\)</span> (as opposed
to having ignored <span class="math inline">\(X_1,\ldots , X_p\)</span>). It represents the difference between the fitted values and the mean: <span class="math inline">\(SSR=\sum\left(\hat{Y}-\overline{Y}\right)^2\)</span> the
<strong>Regression Sum of Squares</strong>. Note that when there are <span class="math inline">\(p&gt;1\)</span> predictors, the fitted equation is no longer a straight line in 2-dimensions.
This makes visualization more difficult, but the concept of distance from observed to predicted value is the same. For the stature example,
<span class="math inline">\(\hat{Y}=\hat{\beta}_0+\hat{\beta}_1X_1+\hat{\beta}_2X_2\)</span> represents a 2-dimensional plane in 3-dimensional space.</p>
<p><span class="math display">\[ TSS = SSE + SSR   \qquad  \qquad  \sum(Y-\overline{Y})^2 = \sum(Y-\hat{Y})^2 + \sum\left(\hat{Y}-\overline{Y}\right)^2   \]</span></p>
<p>The <strong>Total Degrees of Freedom</strong> remains
<span class="math inline">\(df_{\mbox{Total}}=n-1\)</span>. The <strong>Error Degrees of Freedom</strong> is <span class="math inline">\(df_{\mbox{Error}}=n-p&#39;\)</span>.
The <strong>Regression Degrees of Freedom</strong> is <span class="math inline">\(df_{\mbox{Regression}}=p\)</span>. Note that when there is <span class="math inline">\(p=1\)</span> predictor,
this generalizes to simple regression.</p>
<p><span class="math display">\[ df_{\mbox{Total}}= df_{\mbox{Error}} +  df_{\mbox{Regression}}   \qquad  n-1=n-p&#39; +p   \]</span></p>
<p>The Mean Squares for Error and Regression are: <span class="math inline">\(MSE=SSE/(n-p&#39;)\)</span> and <span class="math inline">\(MSR=SSR/p\)</span>. It can be shown that these
mean squares have the following <strong>Expected Values</strong>, average values in repeated sampling at the same
observed <span class="math inline">\(X\)</span> levels.</p>
<p><span class="math display">\[ E\{MSE\}=\sigma^2 \qquad \qquad  E\{MSR\} \geq\sigma^2    \]</span></p>
<p>Note that when <span class="math inline">\(\beta_1= \cdots \beta_p =0\)</span>, then <span class="math inline">\(E\{MSR\}=E\{MSE\}=\sigma^2\)</span>, otherwise <span class="math inline">\(E\{MSR\}&gt;E\{MSE\}\)</span>. A way of
testing whether <span class="math inline">\(\beta_1= \cdots \beta_p =0\)</span> is by the <span class="math inline">\(F\)</span>-test.</p>
<p><span class="math display">\[  H_0: \beta_1=\cdots \beta_p =0   \qquad   H_A: \mbox{ Not all }\beta_j = 0   \]</span>
<span class="math display">\[  \mbox{TS: } F_{obs} = \frac{MSR}{MSE}
\qquad \mbox{RR: } F_{obs} \geq F_{\alpha,p, n-p&#39;}  \qquad P=P\left(F_{p,n-p&#39;} \geq F_{obs}\right)  \]</span></p>
<p>The Analysis of Variance is typically set up in a table as in Table <a href="regression-models.html#tab:anovamlr">9.3</a>.</p>
<table>
<caption><span id="tab:anovamlr">Table 9.3: </span>Analysis of Variance for multiple linear regression</caption>
<thead>
<tr class="header">
<th align="left"></th>
<th align="left">Source</th>
<th align="left"><span class="math inline">\(df\)</span></th>
<th align="left"><span class="math inline">\(SS\)</span></th>
<th align="left"><span class="math inline">\(MS\)</span></th>
<th align="left"><span class="math inline">\(F_{obs}\)</span></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left"></td>
<td align="left">Regression</td>
<td align="left">p</td>
<td align="left">SSR</td>
<td align="left">MSR=SSR/p</td>
<td align="left">F=MSR/MSE</td>
</tr>
<tr class="even">
<td align="left"></td>
<td align="left">Error</td>
<td align="left">n-p’</td>
<td align="left">SSE</td>
<td align="left">MSE=SSE/(n-p’)</td>
<td align="left"></td>
</tr>
<tr class="odd">
<td align="left"></td>
<td align="left">Total</td>
<td align="left">n-1</td>
<td align="left">TSS</td>
<td align="left"></td>
<td align="left"></td>
</tr>
</tbody>
</table>
<p>The <strong>Coefficient of Determination</strong> is labeled <strong><span class="math inline">\(R^2\)</span></strong> for the multiple regression model.
This represents the variation in <span class="math inline">\(Y\)</span> “explained” by <span class="math inline">\(X_1,\ldots ,X_p\)</span>, divided by the total variation in <span class="math inline">\(Y\)</span>.
Note that the <strong>summary</strong> function in R reports “Multiple R-squared” even when there is only a single predictor.</p>
<p><span class="math display">\[ R^2=\frac{\sum\left(\hat{Y}-\overline{Y}\right)^2}{\sum(Y-\overline{Y})^2}=\frac{SSR}{TSS}=1-\frac{SSE}{TSS} \qquad 0 \leq R^2 \leq 1 \]</span></p>
<p><strong>Example 9.7: Stature (Height) as Function of Hand and Foot Length among Females</strong></p>
<p>In a continuation of the Turkish adult females’ model relating stature to hand and foot lengths, the following sums of squares
and <span class="math inline">\(F\)</span>-test are computed.</p>
<p><span class="math display">\[ TSS=\sum(Y-\overline{Y})^2 = 179409 \quad SSE=\sum(Y-\hat{Y})^2= 68924 \quad SSR=\sum\left(\hat{Y}-\overline{Y}\right)^2=110504 \]</span>
<span class="math display">\[ MSE=\frac{68924}{75-3} = 957.3 \qquad MSR=\frac{110504}{2}=55252 \]</span>
<span class="math display">\[ H_0:\beta_1=\beta_2=0\qquad H_A: \beta_1 \mbox{ and/or } \beta_2 \neq 0 \qquad \mbox{TS: } F_{obs}=\frac{55252}{957.3} = 57.72  \]</span>
<span class="math display">\[ \mbox{RR: } F_{obs} \geq F_{.05,2,72}=3.124 \qquad P\left( F_{2,72}\geq 57.72\right)
\approx 0 \]</span></p>
<p>The Coefficient of Determination is <span class="math inline">\(R^2=110504/179409=.616\)</span>, approximately 62% of the variation in height is “explained” by hand and foot length.</p>
<p>The following R code chunk fits the model and gives the <strong>Sequential</strong> and <strong>Partial</strong>
sums of squares.</p>
<div class="sourceCode" id="cb118"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb118-1"><a href="regression-models.html#cb118-1" tabindex="-1"></a><span class="do">## continuation of staturef1</span></span>
<span id="cb118-2"><a href="regression-models.html#cb118-2" tabindex="-1"></a></span>
<span id="cb118-3"><a href="regression-models.html#cb118-3" tabindex="-1"></a>shf.mod1 <span class="ot">&lt;-</span> <span class="fu">lm</span>(height <span class="sc">~</span> handLen <span class="sc">+</span> footLen, <span class="at">data=</span>shf.f)</span>
<span id="cb118-4"><a href="regression-models.html#cb118-4" tabindex="-1"></a><span class="fu">summary</span>(shf.mod1)</span></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = height ~ handLen + footLen, data = shf.f)
## 
## Residuals:
##      Min       1Q   Median       3Q      Max 
## -130.696  -10.662    2.624   11.804   88.218 
## 
## Coefficients:
##             Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept) 743.6072    79.7423   9.325 5.20e-14 ***
## handLen       2.3766     0.4858   4.892 5.89e-06 ***
## footLen       1.7271     0.3743   4.614 1.68e-05 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 30.93 on 72 degrees of freedom
## Multiple R-squared:  0.6162, Adjusted R-squared:  0.6055 
## F-statistic: 57.79 on 2 and 72 DF,  p-value: 1.068e-15</code></pre>
<div class="sourceCode" id="cb120"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb120-1"><a href="regression-models.html#cb120-1" tabindex="-1"></a><span class="fu">anova</span>(shf.mod1)</span></code></pre></div>
<pre><code>## Analysis of Variance Table
## 
## Response: height
##           Df Sum Sq Mean Sq F value    Pr(&gt;F)    
## handLen    1  90191   90191  94.297 1.006e-14 ***
## footLen    1  20364   20364  21.292 1.676e-05 ***
## Residuals 72  68864     956                      
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
<div class="sourceCode" id="cb122"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb122-1"><a href="regression-models.html#cb122-1" tabindex="-1"></a><span class="fu">drop1</span>(shf.mod1, <span class="at">test=</span><span class="st">&quot;F&quot;</span>)</span></code></pre></div>
<pre><code>## Single term deletions
## 
## Model:
## height ~ handLen + footLen
##         Df Sum of Sq   RSS    AIC F value    Pr(&gt;F)    
## &lt;none&gt;               68864 517.68                      
## handLen  1     22891 91755 537.20  23.933 5.891e-06 ***
## footLen  1     20364 89229 535.11  21.292 1.676e-05 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
<p>Note that <span class="math inline">\(SSR=SSR(X_1)+SSR(X_2|X_1) = 90153 + 20351=110504\)</span>. The sums of squares for the <strong>anova</strong> function are the <strong>Sequential Sums of Squares</strong> and
sum up to the Regression Sum of Squares. The <span class="math inline">\(F\)</span>-tests are testing whether the regression coefficients
are 0, given the predictors above each line.</p>
<p>The sums of squares from the <strong>drop1</strong> function are the <strong>Partial Sums of Squares</strong>. They represent the sum of squares for each predictor, given all other predictors. The <span class="math inline">\(F\)</span>-tests for these sums of
squares are eqivalent to the <span class="math inline">\(t\)</span>-tests for the regression coefficients from the <strong>summary</strong> output.</p>
<p><span class="math display">\[ \nabla   \]</span></p>
</div>
<div id="testing-a-subset-of-betas-0" class="section level3 hasAnchor" number="9.2.3">
<h3><span class="header-section-number">9.2.3</span> Testing a Subset of <span class="math inline">\(\beta^s = 0\)</span><a href="regression-models.html#testing-a-subset-of-betas-0" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>The <span class="math inline">\(F\)</span>-test from the Analysis of Variance and the <span class="math inline">\(t\)</span>-tests represent extremes of model testing
(all variables simultaneously versus one-at-a-time). Often interest lies in testing whether a group of predictors
do not improve prediction, after controlling for the remaining predictors.</p>
<p>Suppose that after controlling for <span class="math inline">\(g\)</span> predictors, we wish to test whether the remaining <span class="math inline">\(p-g\)</span> predictors are associated with
<span class="math inline">\(Y\)</span>. That is, we wish to test the following hypotheses.</p>
<p><span class="math display">\[  H_0: \beta_{g+1} = \cdots =\beta_p = 0 \qquad H_A: \mbox{ Not all of } \beta_{g+1}, \ldots, \beta_p=0 \]</span></p>
<p>Note that, the <span class="math inline">\(t\)</span>-tests control for all other predictors, while here, we want to control for only <span class="math inline">\(X_1,\ldots,X_g\)</span>.
To do this, fit two models: the <strong>Complete</strong> or <strong>Full Model</strong> with all <span class="math inline">\(p\)</span> predictors, and the <strong>Reduced Model</strong>
with only the <span class="math inline">\(g\)</span> “control” variables. For each model, obtain the Regression and Error sums of squares, as well as <span class="math inline">\(R^2\)</span>.
Let <span class="math inline">\((F)\)</span> represent the Full model and <span class="math inline">\((R)\)</span> represent the Reduced model.
This leads to the following test statistic and rejection region.</p>
<p><span class="math display">\[ \mbox{TS: } F_{obs} = \frac{\left[\frac{SSE(R)-SSE(F)}{(n-g&#39;)-(n-p&#39;)}\right]}{\left[\frac{SSE(F)}{n-p&#39;}\right]} =
\frac{\left[\frac{SSR(F)-SSR(R)}{p-g}\right]}{\left[\frac{SSE(F)}{n-p&#39;}\right]} =
\frac{\left[\frac{R_F^2-R_R^2}{p-g}\right]}{\left[\frac{1-R_F^2}{n-p&#39;}\right]} \]</span>
<span class="math display">\[ \mbox{RR: } F_{obs} \geq F_{\alpha,p-g,n-p&#39;} \qquad P=P\left(F_{p-g,n-p&#39;}\geq F_{obs}\right) \]</span></p>
<p><strong>Example 9.8: Energy Consumption of Luxury Hotels</strong></p>
<p>A study considered factors relating to Energy Consumption (<span class="math inline">\(Y\)</span>, in millions of kilowatt-hours) for a sample of <span class="math inline">\(n=19\)</span> luxury hotels in Hainan
Province, China <span class="citation">(<a href="#ref-xin_2012">Xin et al. 2012</a>)</span>. The model had 3 predictors: Area (<span class="math inline">\(X_1\)</span>, in 1000s of square meters),
Age (<span class="math inline">\(X_2\)</span>, in years), and Effective number of guest rooms (<span class="math inline">\(X_3\)</span>, # rooms times occupancy rate).</p>
<p>Consider two models: Model 1 with <span class="math inline">\(X_1,X_2,X_3\)</span> as predictors and Model 2 with only <span class="math inline">\(X_1\)</span> as a predictor. The goal is to determine whether
age and/or effective guest rooms is associated with energy consumption, after controlling for the hotel’s size (Area). The data, fitted values
and residuals for Models 1 and 2 are given in Table <a href="regression-models.html#tab:hotelec2">9.4</a>. The fitted equations and Error Sums of Squares are given below directly and in the following R code chunk.
<span class="math inline">\((n=19, p=3, p&#39;=4, g=1)\)</span>.</p>
<p><span class="math display">\[ \mbox{Model 1: Full: } \hat{Y}_F = -2.1320 + 0.1540 X_1 + 0.0959X_2 + 0.0075X_3 \]</span><br />
<span class="math display">\[SSE(F)=67.846 \quad df_E(F)=n-p&#39;=19-4=15  \]</span>
<span class="math display">\[ \mbox{Model 2: Reduced: } \hat{y}_R = -0.5380 + 0.1593 X_1  \]</span> <span class="math display">\[SSE(R)=75.129 \quad df_E(R)=n-g&#39;=19-2=17   \quad p-g=3-1=2  \]</span></p>
<p>The test of <span class="math inline">\(H_0:\beta_2=\beta_3=0\)</span> versus <span class="math inline">\(H_A: \beta_2\)</span> and/or <span class="math inline">\(\beta_3 \neq 0\)</span> is given below.</p>
<p><span class="math display">\[ TS: F_{obs} = \frac{\left[\frac{75.129-67.846}{17-15}\right]}{\left[\frac{67.846}{15}\right]} =
\frac{3.642}{4.523}=0.805 \quad
RR: F_{obs} \geq F_{.05,2,15}=3.682 \]</span>
<span class="math display">\[ P= P(F_{2,15}\geq 0.805)=.4634 \]</span></p>
<p>After controlling for Area, neither Age or Effective guest rooms are associated with Energy Consumption.</p>
<div class="sourceCode" id="cb124"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb124-1"><a href="regression-models.html#cb124-1" tabindex="-1"></a>he <span class="ot">&lt;-</span> <span class="fu">read.csv</span>(<span class="st">&quot;hotel_energy.csv&quot;</span>)</span>
<span id="cb124-2"><a href="regression-models.html#cb124-2" tabindex="-1"></a><span class="fu">head</span>(he, <span class="dv">2</span>)</span></code></pre></div>
<pre><code>##   hotel enrgcons  area age numrooms occrate effrooms
## 1     1  1953916 43000   6      420   0.326   136.92
## 2     2  1045555 19979  16      215   0.630   135.45</code></pre>
<div class="sourceCode" id="cb126"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb126-1"><a href="regression-models.html#cb126-1" tabindex="-1"></a>Y <span class="ot">&lt;-</span> he<span class="sc">$</span>enrgcons<span class="sc">/</span><span class="dv">1000000</span></span>
<span id="cb126-2"><a href="regression-models.html#cb126-2" tabindex="-1"></a>X1 <span class="ot">&lt;-</span> he<span class="sc">$</span>area<span class="sc">/</span><span class="dv">1000</span></span>
<span id="cb126-3"><a href="regression-models.html#cb126-3" tabindex="-1"></a>X2 <span class="ot">&lt;-</span> he<span class="sc">$</span>age</span>
<span id="cb126-4"><a href="regression-models.html#cb126-4" tabindex="-1"></a>X3 <span class="ot">&lt;-</span> he<span class="sc">$</span>effrooms</span>
<span id="cb126-5"><a href="regression-models.html#cb126-5" tabindex="-1"></a></span>
<span id="cb126-6"><a href="regression-models.html#cb126-6" tabindex="-1"></a>he.mod1 <span class="ot">&lt;-</span> <span class="fu">lm</span>(Y <span class="sc">~</span> X1 <span class="sc">+</span> X2 <span class="sc">+</span> X3)</span>
<span id="cb126-7"><a href="regression-models.html#cb126-7" tabindex="-1"></a><span class="fu">summary</span>(he.mod1)</span></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = Y ~ X1 + X2 + X3)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -3.6570 -1.0003  0.0939  1.1978  2.9515 
## 
## Coefficients:
##              Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept) -2.252767   1.781202  -1.265 0.225260    
## X1           0.148709   0.029066   5.116 0.000127 ***
## X2           0.113045   0.134527   0.840 0.413924    
## X3           0.005777   0.007096   0.814 0.428315    
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 2.127 on 15 degrees of freedom
## Multiple R-squared:  0.7946, Adjusted R-squared:  0.7535 
## F-statistic: 19.35 on 3 and 15 DF,  p-value: 2.049e-05</code></pre>
<div class="sourceCode" id="cb128"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb128-1"><a href="regression-models.html#cb128-1" tabindex="-1"></a><span class="fu">anova</span>(he.mod1)</span></code></pre></div>
<pre><code>## Analysis of Variance Table
## 
## Response: Y
##           Df  Sum Sq Mean Sq F value    Pr(&gt;F)    
## X1         1 255.218 255.218 56.4258 1.854e-06 ***
## X2         1   4.286   4.286  0.9475    0.3458    
## X3         1   2.998   2.998  0.6628    0.4283    
## Residuals 15  67.846   4.523                      
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
<div class="sourceCode" id="cb130"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb130-1"><a href="regression-models.html#cb130-1" tabindex="-1"></a>he.mod2 <span class="ot">&lt;-</span> <span class="fu">lm</span>(Y <span class="sc">~</span> X1)</span>
<span id="cb130-2"><a href="regression-models.html#cb130-2" tabindex="-1"></a><span class="fu">summary</span>(he.mod2)</span></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = Y ~ X1)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -4.3559 -0.8721  0.0015  1.3053  3.1488 
## 
## Coefficients:
##             Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept) -0.53804    1.08509  -0.496    0.626    
## X1           0.15925    0.02096   7.599 7.29e-07 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 2.102 on 17 degrees of freedom
## Multiple R-squared:  0.7726, Adjusted R-squared:  0.7592 
## F-statistic: 57.75 on 1 and 17 DF,  p-value: 7.294e-07</code></pre>
<div class="sourceCode" id="cb132"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb132-1"><a href="regression-models.html#cb132-1" tabindex="-1"></a><span class="fu">anova</span>(he.mod2)</span></code></pre></div>
<pre><code>## Analysis of Variance Table
## 
## Response: Y
##           Df  Sum Sq Mean Sq F value    Pr(&gt;F)    
## X1         1 255.218 255.218   57.75 7.294e-07 ***
## Residuals 17  75.129   4.419                      
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
<div class="sourceCode" id="cb134"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb134-1"><a href="regression-models.html#cb134-1" tabindex="-1"></a><span class="fu">anova</span>(he.mod2, he.mod1)</span></code></pre></div>
<pre><code>## Analysis of Variance Table
## 
## Model 1: Y ~ X1
## Model 2: Y ~ X1 + X2 + X3
##   Res.Df    RSS Df Sum of Sq      F Pr(&gt;F)
## 1     17 75.129                           
## 2     15 67.846  2    7.2834 0.8051 0.4654</code></pre>
<table>
<caption><span id="tab:hotelec2">Table 9.4: </span>Data, fitted values and residuals for Full and Reduced models</caption>
<colgroup>
<col width="10%" />
<col width="12%" />
<col width="9%" />
<col width="10%" />
<col width="18%" />
<col width="10%" />
<col width="18%" />
<col width="10%" />
</colgroup>
<thead>
<tr class="header">
<th align="right"><span class="math inline">\(Y\)</span></th>
<th align="right"><span class="math inline">\(X_1\)</span></th>
<th align="right"><span class="math inline">\(X_2\)</span></th>
<th align="right"><span class="math inline">\(X_3\)</span></th>
<th align="right"><span class="math inline">\(\hat{Y}_F\)</span></th>
<th align="right"><span class="math inline">\(e_F\)</span></th>
<th align="right"><span class="math inline">\(\hat{Y}_R\)</span></th>
<th align="right"><span class="math inline">\(e_R\)</span></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="right">1.954</td>
<td align="right">43.000</td>
<td align="right">6</td>
<td align="right">136.92</td>
<td align="right">5.611</td>
<td align="right">-3.657</td>
<td align="right">6.310</td>
<td align="right">-4.356</td>
</tr>
<tr class="even">
<td align="right">1.046</td>
<td align="right">19.979</td>
<td align="right">16</td>
<td align="right">135.45</td>
<td align="right">3.309</td>
<td align="right">-2.264</td>
<td align="right">2.644</td>
<td align="right">-1.598</td>
</tr>
<tr class="odd">
<td align="right">4.245</td>
<td align="right">46.529</td>
<td align="right">7</td>
<td align="right">177.59</td>
<td align="right">6.484</td>
<td align="right">-2.238</td>
<td align="right">6.872</td>
<td align="right">-2.626</td>
</tr>
<tr class="even">
<td align="right">2.126</td>
<td align="right">20.962</td>
<td align="right">6</td>
<td align="right">156.51</td>
<td align="right">2.447</td>
<td align="right">-0.321</td>
<td align="right">2.800</td>
<td align="right">-0.674</td>
</tr>
<tr class="odd">
<td align="right">2.786</td>
<td align="right">24.212</td>
<td align="right">5</td>
<td align="right">330.38</td>
<td align="right">3.822</td>
<td align="right">-1.036</td>
<td align="right">3.318</td>
<td align="right">-0.532</td>
</tr>
<tr class="even">
<td align="right">13.834</td>
<td align="right">112.200</td>
<td align="right">4</td>
<td align="right">385.39</td>
<td align="right">17.111</td>
<td align="right">-3.277</td>
<td align="right">17.330</td>
<td align="right">-3.496</td>
</tr>
<tr class="odd">
<td align="right">5.558</td>
<td align="right">45.000</td>
<td align="right">3</td>
<td align="right">159.25</td>
<td align="right">5.698</td>
<td align="right">-0.140</td>
<td align="right">6.628</td>
<td align="right">-1.070</td>
</tr>
<tr class="even">
<td align="right">4.001</td>
<td align="right">28.548</td>
<td align="right">6</td>
<td align="right">104.02</td>
<td align="right">3.272</td>
<td align="right">0.729</td>
<td align="right">4.008</td>
<td align="right">-0.007</td>
</tr>
<tr class="odd">
<td align="right">4.670</td>
<td align="right">32.865</td>
<td align="right">8</td>
<td align="right">179.50</td>
<td align="right">4.576</td>
<td align="right">0.094</td>
<td align="right">4.696</td>
<td align="right">-0.026</td>
</tr>
<tr class="even">
<td align="right">8.924</td>
<td align="right">59.406</td>
<td align="right">5</td>
<td align="right">290.03</td>
<td align="right">8.822</td>
<td align="right">0.102</td>
<td align="right">8.922</td>
<td align="right">0.002</td>
</tr>
<tr class="odd">
<td align="right">6.866</td>
<td align="right">45.000</td>
<td align="right">10</td>
<td align="right">391.37</td>
<td align="right">7.830</td>
<td align="right">-0.965</td>
<td align="right">6.628</td>
<td align="right">0.237</td>
</tr>
<tr class="even">
<td align="right">6.015</td>
<td align="right">37.435</td>
<td align="right">13</td>
<td align="right">287.17</td>
<td align="right">6.443</td>
<td align="right">-0.428</td>
<td align="right">5.424</td>
<td align="right">0.591</td>
</tr>
<tr class="odd">
<td align="right">8.186</td>
<td align="right">50.828</td>
<td align="right">4</td>
<td align="right">170.03</td>
<td align="right">6.740</td>
<td align="right">1.446</td>
<td align="right">7.556</td>
<td align="right">0.629</td>
</tr>
<tr class="even">
<td align="right">11.736</td>
<td align="right">68.000</td>
<td align="right">13</td>
<td align="right">292.11</td>
<td align="right">11.017</td>
<td align="right">0.720</td>
<td align="right">10.291</td>
<td align="right">1.445</td>
</tr>
<tr class="odd">
<td align="right">14.837</td>
<td align="right">78.868</td>
<td align="right">8</td>
<td align="right">324.54</td>
<td align="right">12.255</td>
<td align="right">2.583</td>
<td align="right">12.022</td>
<td align="right">2.816</td>
</tr>
<tr class="even">
<td align="right">5.366</td>
<td align="right">28.454</td>
<td align="right">13</td>
<td align="right">167.62</td>
<td align="right">4.416</td>
<td align="right">0.950</td>
<td align="right">3.993</td>
<td align="right">1.373</td>
</tr>
<tr class="odd">
<td align="right">13.516</td>
<td align="right">70.000</td>
<td align="right">4</td>
<td align="right">338.53</td>
<td align="right">10.565</td>
<td align="right">2.952</td>
<td align="right">10.610</td>
<td align="right">2.907</td>
</tr>
<tr class="even">
<td align="right">3.884</td>
<td align="right">20.000</td>
<td align="right">5</td>
<td align="right">130.02</td>
<td align="right">2.038</td>
<td align="right">1.847</td>
<td align="right">2.647</td>
<td align="right">1.237</td>
</tr>
<tr class="odd">
<td align="right">10.573</td>
<td align="right">50.000</td>
<td align="right">12</td>
<td align="right">195.57</td>
<td align="right">7.669</td>
<td align="right">2.904</td>
<td align="right">7.425</td>
<td align="right">3.149</td>
</tr>
</tbody>
</table>
<p><span class="math display">\[ \nabla  \]</span></p>
</div>
<div id="models-with-categorical-qualitative-predictors" class="section level3 hasAnchor" number="9.2.4">
<h3><span class="header-section-number">9.2.4</span> Models With Categorical (Qualitative) Predictors<a href="regression-models.html#models-with-categorical-qualitative-predictors" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Often, one or more categorical variables are included in a model. If a categorical variable has <span class="math inline">\(m\)</span>
levels, there will need to be <span class="math inline">\(m-1\)</span> <strong>dummy</strong> or <strong>indicator variables</strong> to reflect the effects of the variable’s levels.
The variable will take on 1
if the <span class="math inline">\(i^{th}\)</span> observation is in that level of the variable, 0 otherwise. Note that one level of the variable
will have <span class="math inline">\(0^s\)</span> for all <span class="math inline">\(m-1\)</span> dummy variables, making it the <strong>reference</strong> category. The <span class="math inline">\(\beta^s\)</span> for the other groups (levels of the qualitative
variable) reflect the difference in the mean for that group with the reference group, controlling for all other predictors.</p>
<p>Note that if the qualitative variable has 2 levels, there will be a single dummy variable, and we can test
for differences in the effects of the 2 levels with a <span class="math inline">\(t\)</span>-test, controlling for all other predictors.
If there are <span class="math inline">\(m-1 &gt; 2\)</span> dummy variables, the <span class="math inline">\(F\)</span>-test can be used to test whether all <span class="math inline">\(m-1\)</span> <span class="math inline">\(\beta^s\)</span> are 0,
controlling for all other predictors. An example is given below.</p>
</div>
<div id="models-with-interaction-terms" class="section level3 hasAnchor" number="9.2.5">
<h3><span class="header-section-number">9.2.5</span> Models With Interaction Terms<a href="regression-models.html#models-with-interaction-terms" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>When the effect of one predictor depends on the level of another predictor (and vice versa), the predictors are
said to <strong>interact</strong>. The way to model interaction(s) is to create a new variable that is the product of
the 2 predictors. Suppose the model has <span class="math inline">\(Y\)</span>, and 2 numeric predictors: <span class="math inline">\(X_1\)</span> and <span class="math inline">\(X_2\)</span>. Create a new predictor <span class="math inline">\(X_3=X_1X_2\)</span>.
Now, consider the following model.</p>
<p><span class="math display">\[   E\{Y\} = \beta_0 + \beta_1X_1+ \beta_2X_2 + \beta_3 X_3 = \beta_0 + \beta_1X_1+ \beta_2X_2 + \beta_3 X_1X_2 =\]</span>
<span class="math display">\[ = \beta_0 + \beta_2X_2 +  \left(\beta_1 + \beta_3X_2\right) X_1  \]</span></p>
<p>The slope with respect to <span class="math inline">\(X_1\)</span> depends on the level of <span class="math inline">\(X_2\)</span>, unless <span class="math inline">\(\beta_3=0\)</span>, which can be tested
with a <span class="math inline">\(t\)</span>-test of <span class="math inline">\(H_0:\beta_3=0\)</span>. This logic extends to
qualitative variables as well. Create cross-product terms between numeric (or other categorical) predictors with the
<span class="math inline">\(m-1\)</span> dummy variables representing the qualitative predictor. Then the <span class="math inline">\(t\)</span>-test (<span class="math inline">\(m-1=1\)</span>) or <span class="math inline">\(F\)</span>-test (<span class="math inline">\(m-1\geq 2\)</span>) can be
conducted to test for interactions among predictors. This is demonstrated by adding males to the stature data below.</p>
<p><strong>Example 9.9: Heights, Hand and Foot Lengths in Males and Females</strong></p>
<p>In the stature study <span class="citation">(<a href="#ref-sanli_2005">Sanli et al. 2015</a>)</span>, there were also 80 males, for a total of <span class="math inline">\(n=75+80=155\)</span> adults.
For these models, <span class="math inline">\(Y\)</span> is height, <span class="math inline">\(X_1\)</span> is hand length, and <span class="math inline">\(X_2\)</span> is foot length.
Create the dummy (indicator) variable <span class="math inline">\(X_3=1\)</span> if male, <span class="math inline">\(X_3=0\)</span> if female. Then consider three models: Common slopes and intercept by gender
(Model 1), Common slopes but different intercepts by gender (Model 2), and Different slopes and intercepts by gender (Model 3).
The models are given below.</p>
<p><span class="math display">\[ \mbox{Model 1: } E\{Y\} = \beta_0 + \beta_1 X_1 + \beta_2X_2  \]</span></p>
<p><span class="math display">\[ \mbox{Model 2: } E\{Y\} = \beta_0 + \beta_1 X_1 + \beta_2X_2 + \beta_3X_3 \]</span>
<span class="math display">\[  \mbox{Females: } E\{Y\} = \beta_0 + \beta_1 X_1 + \beta_2X_2
\quad \mbox{Males: } E\{Y\} = \left(\beta_0 + \beta_3\right) + \beta_1 X_1 + \beta_2X_2 \]</span></p>
<p><span class="math display">\[ \mbox{Model 3: } E\{Y\} = \beta_0 + \beta_1 X_1 + \beta_2X_2 + \beta_3X_3 + \beta_4X_1X_3 + \beta_5 X_2X_3 \]</span></p>
<p><span class="math display">\[ \mbox{Females: } E\{Y\} = \beta_0 + \beta_1 X_1 + \beta_2X_2 \]</span></p>
<p><span class="math display">\[ \mbox{Males: } E\{Y\} = \left(\beta_0 + \beta_3\right) + \left(\beta_1+\beta_4\right) X_1 +
\left(\beta_2 + \beta_5\right)X_2 \]</span></p>
<p>The fitted equations and their Error Sums of Squares are given below (the regression coefficients are taken from the R output given below).</p>
<p><span class="math display">\[ \mbox{Model 1: } \hat{Y}_F = \hat{Y}_M = 372.64 + 3.32 X_1 + 2.58 X_2\]</span>
<span class="math display">\[  SSE_1=189029 \quad df_{E1}=155-3=152 \]</span></p>
<p><span class="math display">\[ \mbox{Model 2: } \hat{Y}_F=581.99+ 2.81 X_1 + 2.06X_2 \qquad \hat{Y}_M=621.55 + 2.81 X_1 + 2.06X_2\]</span> <span class="math display">\[  SSE_2=165341 \quad df_{E2}=155-4 = 151 \]</span></p>
<p><span class="math display">\[ \mbox{Model 3: } \hat{Y}_F=743.97+ 2.38 X_1 + 1.73X_2 \qquad \hat{Y}_M=439.27 + 3.29 X_1 + 2.38X_2 \]</span> <span class="math display">\[  SSE_3=157360 \quad df_{E3}=155-6 = 149 \]</span></p>
<p>Tests comparing the different models include Model 2 versus Model 1, where the null hypothesis is common slopes and intercepts (Model 1) and
the alternative is common slopes and different intercepts (Model 2). The null hypothesis is <span class="math inline">\(H_0:\beta_3=0\)</span>.</p>
<p><span class="math display">\[ TS: F_{12}=\frac{\left[\frac{189029-165341}{152-151}\right]}{\left[\frac{165341}{151}\right]}=\frac{23688}{1095}=21.63
\quad RR: F_{12} \geq F_{.05,1,151}=3.904 \]</span></p>
<p>A second test comparing the different models includes Model 3 versus Model 2, where the null hypothesis is common slopes and different intercepts (Model 2) and
the alternative is different slopes and intercepts (Model 3). The null hypothesis is <span class="math inline">\(H_0:\beta_4=\beta_5=0\)</span>.</p>
<p><span class="math display">\[ TS: F_{23}=\frac{\left[\frac{165341-157360}{151-149}\right]}{\left[\frac{157360}{149}\right]}=\frac{3990.5}{1056}=3.78
\quad RR: F_{23} \geq F_{.05,2,149}=3.057 \quad P=.0251 \]</span></p>
<p>The “full model” allowing for different slopes and intercepts for males and females gives the best fit.
These models are fit and compared in the following R code chunk.</p>
<div class="sourceCode" id="cb136"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb136-1"><a href="regression-models.html#cb136-1" tabindex="-1"></a>shf <span class="ot">&lt;-</span> <span class="fu">read.csv</span>(<span class="st">&quot;stature_hand_foot.csv&quot;</span>)</span>
<span id="cb136-2"><a href="regression-models.html#cb136-2" tabindex="-1"></a>shf<span class="sc">$</span>male <span class="ot">&lt;-</span> <span class="fu">ifelse</span>(shf<span class="sc">$</span>gender<span class="sc">==</span><span class="dv">1</span>,<span class="dv">1</span>,<span class="dv">0</span>)   <span class="co"># If gender=1, Male (male=1), if gender=2, Female (male=0)</span></span>
<span id="cb136-3"><a href="regression-models.html#cb136-3" tabindex="-1"></a></span>
<span id="cb136-4"><a href="regression-models.html#cb136-4" tabindex="-1"></a><span class="do">## Model 1: Common slopes and intercepts by gender</span></span>
<span id="cb136-5"><a href="regression-models.html#cb136-5" tabindex="-1"></a>shfm.mod1 <span class="ot">&lt;-</span> <span class="fu">lm</span>(height <span class="sc">~</span> handLen <span class="sc">+</span> footLen, <span class="at">data=</span>shf)</span>
<span id="cb136-6"><a href="regression-models.html#cb136-6" tabindex="-1"></a><span class="fu">summary</span>(shfm.mod1)</span></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = height ~ handLen + footLen, data = shf)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -168.27  -15.14    2.99   18.58  110.82 
## 
## Coefficients:
##             Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept) 372.5568    43.2445   8.615 8.36e-15 ***
## handLen       3.3187     0.3460   9.592  &lt; 2e-16 ***
## footLen       2.5809     0.2489  10.371  &lt; 2e-16 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 35.25 on 152 degrees of freedom
## Multiple R-squared:  0.8609, Adjusted R-squared:  0.8591 
## F-statistic: 470.4 on 2 and 152 DF,  p-value: &lt; 2.2e-16</code></pre>
<div class="sourceCode" id="cb138"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb138-1"><a href="regression-models.html#cb138-1" tabindex="-1"></a><span class="fu">anova</span>(shfm.mod1)</span></code></pre></div>
<pre><code>## Analysis of Variance Table
## 
## Response: height
##            Df  Sum Sq Mean Sq F value    Pr(&gt;F)    
## handLen     1 1035641 1035641  833.26 &lt; 2.2e-16 ***
## footLen     1  133675  133675  107.55 &lt; 2.2e-16 ***
## Residuals 152  188918    1243                      
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
<div class="sourceCode" id="cb140"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb140-1"><a href="regression-models.html#cb140-1" tabindex="-1"></a><span class="do">## Model 2: Common slopes, different intercepts by gender</span></span>
<span id="cb140-2"><a href="regression-models.html#cb140-2" tabindex="-1"></a>shfm.mod2 <span class="ot">&lt;-</span> <span class="fu">lm</span>(height <span class="sc">~</span> handLen <span class="sc">+</span> footLen <span class="sc">+</span> male, <span class="at">data=</span>shf)</span>
<span id="cb140-3"><a href="regression-models.html#cb140-3" tabindex="-1"></a><span class="fu">summary</span>(shfm.mod2)</span></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = height ~ handLen + footLen + male, data = shf)
## 
## Residuals:
##      Min       1Q   Median       3Q      Max 
## -143.193  -16.486    2.571   14.510  100.705 
## 
## Coefficients:
##             Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept) 581.8840    60.5888   9.604  &lt; 2e-16 ***
## handLen       2.8124     0.3424   8.214 8.89e-14 ***
## footLen       2.0641     0.2586   7.982 3.36e-13 ***
## male         39.5600     8.5034   4.652 7.12e-06 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 33.08 on 151 degrees of freedom
## Multiple R-squared:  0.8783, Adjusted R-squared:  0.8759 
## F-statistic: 363.4 on 3 and 151 DF,  p-value: &lt; 2.2e-16</code></pre>
<div class="sourceCode" id="cb142"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb142-1"><a href="regression-models.html#cb142-1" tabindex="-1"></a><span class="fu">anova</span>(shfm.mod2)</span></code></pre></div>
<pre><code>## Analysis of Variance Table
## 
## Response: height
##            Df  Sum Sq Mean Sq F value    Pr(&gt;F)    
## handLen     1 1035641 1035641 946.424 &lt; 2.2e-16 ***
## footLen     1  133675  133675 122.159 &lt; 2.2e-16 ***
## male        1   23684   23684  21.644 7.122e-06 ***
## Residuals 151  165234    1094                      
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
<div class="sourceCode" id="cb144"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb144-1"><a href="regression-models.html#cb144-1" tabindex="-1"></a><span class="do">## Model 3: Different slopes and intercepts by gender</span></span>
<span id="cb144-2"><a href="regression-models.html#cb144-2" tabindex="-1"></a>shfm.mod3 <span class="ot">&lt;-</span> <span class="fu">lm</span>(height <span class="sc">~</span> handLen <span class="sc">+</span> footLen <span class="sc">+</span> male <span class="sc">+</span> <span class="fu">I</span>(handLen<span class="sc">*</span>male) <span class="sc">+</span> <span class="fu">I</span>(footLen<span class="sc">*</span>male), <span class="at">data=</span>shf)</span>
<span id="cb144-3"><a href="regression-models.html#cb144-3" tabindex="-1"></a><span class="fu">summary</span>(shfm.mod3)</span></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = height ~ handLen + footLen + male + I(handLen * 
##     male) + I(footLen * male), data = shf)
## 
## Residuals:
##      Min       1Q   Median       3Q      Max 
## -130.696  -13.847    1.481   13.508  102.582 
## 
## Coefficients:
##                    Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)        743.6072    83.7738   8.876 2.02e-15 ***
## handLen              2.3766     0.5104   4.657 7.06e-06 ***
## footLen              1.7271     0.3932   4.392 2.12e-05 ***
## male              -303.9922   125.5620  -2.421   0.0167 *  
## I(handLen * male)    0.9090     0.6807   1.335   0.1838    
## I(footLen * male)    0.6532     0.5159   1.266   0.2075    
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 32.49 on 149 degrees of freedom
## Multiple R-squared:  0.8842, Adjusted R-squared:  0.8803 
## F-statistic: 227.5 on 5 and 149 DF,  p-value: &lt; 2.2e-16</code></pre>
<div class="sourceCode" id="cb146"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb146-1"><a href="regression-models.html#cb146-1" tabindex="-1"></a><span class="fu">anova</span>(shfm.mod3)</span></code></pre></div>
<pre><code>## Analysis of Variance Table
## 
## Response: height
##                    Df  Sum Sq Mean Sq  F value    Pr(&gt;F)    
## handLen             1 1035641 1035641 981.0914 &lt; 2.2e-16 ***
## footLen             1  133675  133675 126.6338 &lt; 2.2e-16 ***
## male                1   23684   23684  22.4363 5.018e-06 ***
## I(handLen * male)   1    6258    6258   5.9281   0.01608 *  
## I(footLen * male)   1    1692    1692   1.6029   0.20747    
## Residuals         149  157285    1056                       
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
<div class="sourceCode" id="cb148"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb148-1"><a href="regression-models.html#cb148-1" tabindex="-1"></a><span class="fu">anova</span>(shfm.mod1, shfm.mod2)      <span class="do">## Test H0: beta3=0</span></span></code></pre></div>
<pre><code>## Analysis of Variance Table
## 
## Model 1: height ~ handLen + footLen
## Model 2: height ~ handLen + footLen + male
##   Res.Df    RSS Df Sum of Sq      F    Pr(&gt;F)    
## 1    152 188918                                  
## 2    151 165234  1     23684 21.644 7.122e-06 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
<div class="sourceCode" id="cb150"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb150-1"><a href="regression-models.html#cb150-1" tabindex="-1"></a><span class="fu">anova</span>(shfm.mod2, shfm.mod3)      <span class="do">## Test H0: beta4=beta5=0</span></span></code></pre></div>
<pre><code>## Analysis of Variance Table
## 
## Model 1: height ~ handLen + footLen + male
## Model 2: height ~ handLen + footLen + male + I(handLen * male) + I(footLen * 
##     male)
##   Res.Df    RSS Df Sum of Sq      F  Pr(&gt;F)  
## 1    151 165234                              
## 2    149 157285  2    7949.8 3.7655 0.02539 *
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
<p><span class="math display">\[ \nabla  \]</span></p>
</div>
</div>
<div id="logistic-regression" class="section level2 hasAnchor" number="9.3">
<h2><span class="header-section-number">9.3</span> Logistic Regression<a href="regression-models.html#logistic-regression" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>When the response variable is binary (presence/absence of a characteristic), one model that is often fit is the logistic regression model.
It fits the probability of a “Success” as an S-shaped, logistic function. In this formulation, we let <span class="math inline">\(\pi\)</span> represent the probability
of Success, which is bounded between 0 and 1. Define the <strong>odds</strong> of Success as <span class="math inline">\(o = \pi / (1 - \pi)\)</span> which represents
the number of successes for every failure. Note that if <span class="math inline">\(\pi = 0.9\)</span>, then <span class="math inline">\(o = .9/.1=9\)</span>, and we expect 9 successes for every failure.
If <span class="math inline">\(\pi = 0.1\)</span>, then <span class="math inline">\(o = .1/.9 = 1/9\)</span>, and we expect 1/9 successes for every failure. Odds can range from 0 to <span class="math inline">\(\infty\)</span>, and
the log odds, also known as <strong>logit</strong> can range from <span class="math inline">\(-\infty\)</span> to <span class="math inline">\(\infty\)</span>.
Thus, while probabilities are restricted to be between 0 and 1, and odds are restricted to be positive, logits are not restricted and can be used in modelling the relation with the predictors.
After the model is fit, we can back transform to obtain fitted probabilities.</p>
<p>The model is given below.
<span class="math display">\[ \mbox{logit}\left(\pi \right) = \mbox{log}\left(\frac{\pi}{1-\pi}\right) = \beta_0 + \beta_1 X_1 + \cdots + \beta_p X_p \qquad
\Rightarrow \qquad \pi = \frac{e^{\beta_0 + \beta_1 X_1 + \cdots + \beta_p X_p}}{1+e^{\beta_0 + \beta_1 X_1 + \cdots + \beta_p X_p}} \]</span></p>
<p>Statistical software packages can be used to obtain maximum likelihood estimates of the <span class="math inline">\(\beta^s\)</span> and their estimated standard errors.
Unlike linear regression, there are no closed form solutions, and they are obtained iteratively. The predicted probability
of success for the <span class="math inline">\(i^{\mbox{th}}\)</span>
observation with predictor variables <span class="math inline">\(X_{i1},\ldots ,X_{ip}\)</span> is computed as follows (recall that the observed <span class="math inline">\(y_i\)</span> is 0 or 1).</p>
<p><span class="math display">\[ \hat{\pi}_i = \frac{e^{\hat{\beta}_0 + \hat{\beta}_1 X_{i1} + \cdots + \hat{\beta}_p X_{ip}}}{1+e^{\hat{\beta}_0 + \hat{\beta}_1 X_{i1} + \cdots + \hat{\beta}_p X_{ip}}} \qquad i=1,\ldots ,n \]</span></p>
<p>Tests can be conducted as in linear regression for individual coefficients, all coefficients, and subsets of coefficients.
They use different distributions for the tests (<span class="math inline">\(z\)</span>-tests in place of <span class="math inline">\(t\)</span>-tests and Chi-square tests in place of <span class="math inline">\(F\)</span>-tests).</p>
<p><strong>Wald tests</strong> are printed out automatically by any standard statistical software package and can be reported as a <span class="math inline">\(z\)</span>-statistic
(R and Stata) or as a Chi-square statistic (SAS and SPSS). These are similar to the <span class="math inline">\(t\)</span>-statistics in linear regression for the
individual regression coefficients.</p>
<p><span class="math display">\[ z-\mbox{test: } H_0: \beta_j = 0 \qquad  H_A: \beta_j \neq 0 \qquad \mbox{TS: } z_j = \frac{\hat{\beta}_j}{\widehat{SE}\{\hat{\beta}_j\}} \]</span>
<span class="math display">\[ \mbox{RR: } |z_j| \geq z_{\alpha/2} \qquad
P=2P\left(Z\geq |z_j|\right) \]</span></p>
<p><span class="math display">\[ \chi^2-\mbox{test: } H_0: \beta_j = 0 \qquad  H_A: \beta_j \neq 0 \qquad \mbox{TS: } X^2_j = \left(\frac{\hat{\beta}_j}{\widehat{SE}\{\hat{\beta}_j\}}\right)^2 \]</span>
<span class="math display">\[ \mbox{RR: } X^2_j \geq \chi^2_{1,\alpha} \quad
P=P\left(\chi^2_{1}\geq X^2_j\right) \]</span></p>
<p>Tests that all coefficients (besides <span class="math inline">\(\beta_0\)</span>) and that a subset of coefficients are 0 can be conducted as
<strong>Likelihood-Ratio tests</strong>. Once the regression coefficients are computed for the various models, and used to obtain
the predicted values <span class="math inline">\(\hat{\pi}_i\)</span>, the likelihood and the log-likelihood for the model is obtained as follows by standard packages.</p>
<p><span class="math display">\[ \mbox{Likelihood: } L = \prod_{i=1}^n \hat{\pi}^{y_i}\left(1-\hat{\pi}_i\right)^{1-y_i} \qquad \mbox{log-likelihood: } l = log(L) \]</span></p>
<p>Then for any Full and Reduced models, we can compute <span class="math inline">\(l_F\)</span> and <span class="math inline">\(l_R\)</span>, where necessarily <span class="math inline">\(l_F \geq l_R\)</span>.
To test <span class="math inline">\(H_0:\beta_1 = \cdots = \beta_p=0\)</span>, we fit a full model with all <span class="math inline">\(p\)</span> predictors and a reduced model with
only an intercept (probability of success is equal for all individual cases). The test is conducted as follows.</p>
<p><span class="math display">\[ H_0:\beta_1 = \cdots = \beta_p=0 \quad H_A: \mbox{ Not all } \beta_j = 0 \qquad \mbox{TS: } X^2 = -2\left(l_R - l_F\right) \]</span>
<span class="math display">\[ \mbox{RR: } X^2\geq \chi^2_{\alpha,p}
\qquad P=P\left(\chi^2_{p}\geq X^2\right) \]</span></p>
<p>We will demonstrate these with two examples, one with a single predictor, the other with a set of predictors.</p>
<p><strong>Example 9.10: Pre-Challenger O-Ring Failure and Temperature</strong></p>
<p>Prior to the space shuttle Challenger’s explosion after lift-off in January, 1986, the shuttle had flown on <span class="math inline">\(n=23\)</span> successful flights
<span class="citation">(<a href="#ref-dalal_1989">Dalal, Fowlkes, and Hoadley 1989</a>)</span>.
The flights were classified by whether there had been field-joint O-ring failure in the connection of the shuttle to the solid rocket booster
(Y=1 if yes, 0 if no) and the temperature at lift-off (X=degrees F). Data are given in Table <a href="regression-models.html#tab:challenger1">9.5</a> along with fitted probability of an O-ring failure. Note that the “Success” in this case is
actually an unfavorable event, and the model is relating the probability of the event occurring as a function of temperature.
The R program and output are given below. The result is that there is a significant association between temperature and the event of O-ring failure.
Also, since there is evidence that <span class="math inline">\(\beta_1 &lt;0\)</span>, we can conclude that the probability of O-ring failure decreases as temperature increases. The morning of the Challenger incident was much colder than previous launch dates.
A plot of the data and the fitted equation is given in Figure <a href="regression-models.html#fig:challenger1">9.5</a>. The fitted equation is given below.</p>
<p><span class="math display">\[ \hat{\pi} = \frac{e^{15.0429-0.2322X}}{1+e^{15.0429-0.2322X}} \]</span>
The following R code chunk gives the fitted model and <span class="math inline">\(z\)</span>-test for the temperature effect.</p>
<pre><code>## 
## Call:
## glm(formula = ORFail ~ tempF, family = binomial(&quot;logit&quot;), data = chal)
## 
## Coefficients:
##             Estimate Std. Error z value Pr(&gt;|z|)  
## (Intercept)  15.0429     7.3786   2.039   0.0415 *
## tempF        -0.2322     0.1082  -2.145   0.0320 *
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## (Dispersion parameter for binomial family taken to be 1)
## 
##     Null deviance: 28.267  on 22  degrees of freedom
## Residual deviance: 20.315  on 21  degrees of freedom
## AIC: 24.315
## 
## Number of Fisher Scoring iterations: 5</code></pre>
<pre><code>## Waiting for profiling to be done...</code></pre>
<pre><code>##                  2.5 %      97.5 %
## (Intercept)  3.3305848 34.34215133
## tempF       -0.5154718 -0.06082076</code></pre>
<table>
<caption><span id="tab:challenger1">Table 9.5: </span>Pre-Challenger Temperatures, O-ring Failures, and fitted probabilities</caption>
<thead>
<tr class="header">
<th align="right">Flight</th>
<th align="right">Temp (F)</th>
<th align="right">OR Fail</th>
<th align="right">Fit Prob</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="right">1</td>
<td align="right">66</td>
<td align="right">0</td>
<td align="right">0.430</td>
</tr>
<tr class="even">
<td align="right">2</td>
<td align="right">70</td>
<td align="right">1</td>
<td align="right">0.230</td>
</tr>
<tr class="odd">
<td align="right">3</td>
<td align="right">69</td>
<td align="right">0</td>
<td align="right">0.274</td>
</tr>
<tr class="even">
<td align="right">4</td>
<td align="right">68</td>
<td align="right">0</td>
<td align="right">0.322</td>
</tr>
<tr class="odd">
<td align="right">5</td>
<td align="right">67</td>
<td align="right">0</td>
<td align="right">0.375</td>
</tr>
<tr class="even">
<td align="right">6</td>
<td align="right">72</td>
<td align="right">0</td>
<td align="right">0.158</td>
</tr>
<tr class="odd">
<td align="right">7</td>
<td align="right">73</td>
<td align="right">0</td>
<td align="right">0.130</td>
</tr>
<tr class="even">
<td align="right">8</td>
<td align="right">70</td>
<td align="right">0</td>
<td align="right">0.230</td>
</tr>
<tr class="odd">
<td align="right">9</td>
<td align="right">57</td>
<td align="right">1</td>
<td align="right">0.859</td>
</tr>
<tr class="even">
<td align="right">10</td>
<td align="right">63</td>
<td align="right">1</td>
<td align="right">0.603</td>
</tr>
<tr class="odd">
<td align="right">11</td>
<td align="right">70</td>
<td align="right">1</td>
<td align="right">0.230</td>
</tr>
<tr class="even">
<td align="right">12</td>
<td align="right">78</td>
<td align="right">0</td>
<td align="right">0.045</td>
</tr>
<tr class="odd">
<td align="right">13</td>
<td align="right">67</td>
<td align="right">0</td>
<td align="right">0.375</td>
</tr>
<tr class="even">
<td align="right">14</td>
<td align="right">53</td>
<td align="right">1</td>
<td align="right">0.939</td>
</tr>
<tr class="odd">
<td align="right">15</td>
<td align="right">67</td>
<td align="right">0</td>
<td align="right">0.375</td>
</tr>
<tr class="even">
<td align="right">16</td>
<td align="right">75</td>
<td align="right">0</td>
<td align="right">0.086</td>
</tr>
<tr class="odd">
<td align="right">17</td>
<td align="right">70</td>
<td align="right">0</td>
<td align="right">0.230</td>
</tr>
<tr class="even">
<td align="right">18</td>
<td align="right">81</td>
<td align="right">0</td>
<td align="right">0.023</td>
</tr>
<tr class="odd">
<td align="right">19</td>
<td align="right">76</td>
<td align="right">0</td>
<td align="right">0.069</td>
</tr>
<tr class="even">
<td align="right">20</td>
<td align="right">79</td>
<td align="right">0</td>
<td align="right">0.036</td>
</tr>
<tr class="odd">
<td align="right">21</td>
<td align="right">75</td>
<td align="right">1</td>
<td align="right">0.086</td>
</tr>
<tr class="even">
<td align="right">22</td>
<td align="right">76</td>
<td align="right">0</td>
<td align="right">0.069</td>
</tr>
<tr class="odd">
<td align="right">23</td>
<td align="right">58</td>
<td align="right">1</td>
<td align="right">0.829</td>
</tr>
</tbody>
</table>
<div class="figure" style="text-align: center"><span style="display:block;" id="fig:challenger1"></span>
<img src="STA2170bookdownproj_files/figure-html/challenger1-1.png" alt="Pre-Challenger observed O-ring outcomes, temperature and fitted probability of O-ing incident" width="80%" />
<p class="caption">
Figure 9.5: Pre-Challenger observed O-ring outcomes, temperature and fitted probability of O-ing incident
</p>
</div>
<p><span class="math display">\[ \nabla  \]</span></p>
<p><strong>Example 9.11: Presence/Absence of Gold Deposits in India</strong></p>
<p>A study was conducted <span class="citation">(<a href="#ref-sahoo_1999">Sahoo and Pandalai 1999</a>)</span> to determine whether the presence/absence of gold at locations in India is related to three predictors: Arsenic level (<span class="math inline">\(X_1\)</span>),
Antimony level (<span class="math inline">\(X_2\)</span>) and lineament presence (<span class="math inline">\(X_3=1\)</span> if yes, 0 if no) based on a sample of <span class="math inline">\(n=64\)</span> locations.
We consider three models: one with only an intercept, one with only arsenic as a predictor, and one with all 3 predictors.</p>
<p><span class="math display">\[ \mbox{Model 0: } \pi = \frac{e^{\beta_0}}{1+e^{\beta_0}} \quad
\mbox{Model 1: } \pi = \frac{e^{\beta_0 + \beta_1 X_1}}{1+e^{\beta_0 + \beta_1 X_1}} \quad
\mbox{Model 3: } \pi = \frac{e^{\beta_0 + \beta_1 X_1 + \beta_2X_2 + \beta_3 X_3}}{1+e^{\beta_0 + \beta_1 X_1 + \beta_2X_2 + \beta_3 X_3}}
\]</span></p>
<p>First, we will compare Models 0 and 3 to test <span class="math inline">\(H_0:\beta_1=\beta_2=\beta_3=0\)</span>, that is that gold presence is not associated with any of the predictors.
Second, we will compare Models 1 and 3 to test <span class="math inline">\(H_0:\beta_2=\beta_3=0\)</span>, that is that gold presence is not associated with antimony or lineament,
after controlling for arsenic. The log-likelihoods for the three models are <span class="math inline">\(l_0=-43.8601\)</span>, <span class="math inline">\(l_1=-11.3014\)</span>, and <span class="math inline">\(l_3=-7.0972\)</span>, respectively.
Now, we conduct the two tests described above. Note that for the second test, the degrees of freedom is the number of restrictions under the null
hypothesis, which is 2 (<span class="math inline">\(\beta_2=\beta_3=0\)</span>).</p>
<p><span class="math display">\[  H_0:\beta_1=\beta_2=\beta_3=0 \qquad \mbox{TS: } X^2=-2\left((l_0-l_3\right)=-2(-43.8601-(-7.0972))=73.526 \]</span></p>
<p><span class="math display">\[ \mbox{RR: } X^2 \geq \chi^2_{.05,3}=7.815 \qquad
     P=P\left(\chi^2_{3} \geq 73.526\right) &lt; .0001 \]</span></p>
<p><span class="math display">\[  H_0:\beta_2=\beta_3=0 \qquad \mbox{TS: } X^2=-2\left((l_1-l_3\right)=-2(-11.3014-(-7.0972))=8.408 \]</span>
<span class="math display">\[ \mbox{RR: } X^2 \geq \chi^2_{.05,2}=5.991 \qquad
     P=P\left(\chi^2_{2} \geq 8.408\right) = .0149 \]</span></p>
<p>The R code chunk and output are given below. Note that the p-values for the Wald tests of <span class="math inline">\(\beta_2=0\)</span> (<span class="math inline">\(P=.0516\)</span>) and <span class="math inline">\(\beta_3=0\)</span> (<span class="math inline">\(P=.0909\)</span>)
for Model 3 are both above .0500. Those tests are controlling for each other, while the Chi-square test above tests that they are both simultaneously 0,
controlling only for Arsenic (<span class="math inline">\(P=.0149\)</span>).</p>
<div class="sourceCode" id="cb155"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb155-1"><a href="regression-models.html#cb155-1" tabindex="-1"></a>gold.data <span class="ot">&lt;-</span> <span class="fu">read.table</span>(<span class="st">&quot;gold_target1.dat&quot;</span>,</span>
<span id="cb155-2"><a href="regression-models.html#cb155-2" tabindex="-1"></a>                       <span class="at">header=</span>F, </span>
<span id="cb155-3"><a href="regression-models.html#cb155-3" tabindex="-1"></a>                      <span class="at">col.names=</span><span class="fu">c</span>(<span class="st">&quot;arsenic&quot;</span>,<span class="st">&quot;antimony&quot;</span>,<span class="st">&quot;lineament&quot;</span>,<span class="st">&quot;gold&quot;</span>))</span>
<span id="cb155-4"><a href="regression-models.html#cb155-4" tabindex="-1"></a></span>
<span id="cb155-5"><a href="regression-models.html#cb155-5" tabindex="-1"></a>gold.mod0 <span class="ot">&lt;-</span> <span class="fu">glm</span>(gold <span class="sc">~</span> <span class="dv">1</span>, <span class="fu">binomial</span>(<span class="st">&quot;logit&quot;</span>), <span class="at">data=</span>gold.data)</span>
<span id="cb155-6"><a href="regression-models.html#cb155-6" tabindex="-1"></a><span class="fu">summary</span>(gold.mod0)</span></code></pre></div>
<pre><code>## 
## Call:
## glm(formula = gold ~ 1, family = binomial(&quot;logit&quot;), data = gold.data)
## 
## Coefficients:
##             Estimate Std. Error z value Pr(&gt;|z|)
## (Intercept)  -0.2513     0.2520  -0.997    0.319
## 
## (Dispersion parameter for binomial family taken to be 1)
## 
##     Null deviance: 87.72  on 63  degrees of freedom
## Residual deviance: 87.72  on 63  degrees of freedom
## AIC: 89.72
## 
## Number of Fisher Scoring iterations: 3</code></pre>
<div class="sourceCode" id="cb157"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb157-1"><a href="regression-models.html#cb157-1" tabindex="-1"></a>(ll.mod0 <span class="ot">&lt;-</span> <span class="fu">logLik</span>(gold.mod0))</span></code></pre></div>
<pre><code>## &#39;log Lik.&#39; -43.86011 (df=1)</code></pre>
<div class="sourceCode" id="cb159"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb159-1"><a href="regression-models.html#cb159-1" tabindex="-1"></a>gold.mod1 <span class="ot">&lt;-</span> <span class="fu">glm</span>(gold <span class="sc">~</span> arsenic, <span class="fu">binomial</span>(<span class="st">&quot;logit&quot;</span>), <span class="at">data=</span>gold.data)</span></code></pre></div>
<pre><code>## Warning: glm.fit: fitted probabilities numerically 0 or 1 occurred</code></pre>
<div class="sourceCode" id="cb161"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb161-1"><a href="regression-models.html#cb161-1" tabindex="-1"></a><span class="fu">summary</span>(gold.mod1)</span></code></pre></div>
<pre><code>## 
## Call:
## glm(formula = gold ~ arsenic, family = binomial(&quot;logit&quot;), data = gold.data)
## 
## Coefficients:
##             Estimate Std. Error z value Pr(&gt;|z|)    
## (Intercept)  -3.9460     0.9641  -4.093 4.26e-05 ***
## arsenic       1.3456     0.3354   4.012 6.02e-05 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## (Dispersion parameter for binomial family taken to be 1)
## 
##     Null deviance: 87.720  on 63  degrees of freedom
## Residual deviance: 22.603  on 62  degrees of freedom
## AIC: 26.603
## 
## Number of Fisher Scoring iterations: 8</code></pre>
<div class="sourceCode" id="cb163"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb163-1"><a href="regression-models.html#cb163-1" tabindex="-1"></a>(ll.mod1 <span class="ot">&lt;-</span> <span class="fu">logLik</span>(gold.mod1))</span></code></pre></div>
<pre><code>## &#39;log Lik.&#39; -11.30143 (df=2)</code></pre>
<div class="sourceCode" id="cb165"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb165-1"><a href="regression-models.html#cb165-1" tabindex="-1"></a>gold.mod3 <span class="ot">&lt;-</span> <span class="fu">glm</span>(gold <span class="sc">~</span> arsenic <span class="sc">+</span> antimony <span class="sc">+</span> lineament, <span class="fu">binomial</span>(<span class="st">&quot;logit&quot;</span>), <span class="at">data=</span>gold.data)</span></code></pre></div>
<pre><code>## Warning: glm.fit: fitted probabilities numerically 0 or 1 occurred</code></pre>
<div class="sourceCode" id="cb167"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb167-1"><a href="regression-models.html#cb167-1" tabindex="-1"></a><span class="fu">summary</span>(gold.mod3)</span></code></pre></div>
<pre><code>## 
## Call:
## glm(formula = gold ~ arsenic + antimony + lineament, family = binomial(&quot;logit&quot;), 
##     data = gold.data)
## 
## Coefficients:
##             Estimate Std. Error z value Pr(&gt;|z|)  
## (Intercept)  -7.6096     3.1661  -2.403   0.0162 *
## arsenic       1.2046     0.4899   2.459   0.0139 *
## antimony      1.4210     0.7301   1.946   0.0516 .
## lineament     3.1973     1.8911   1.691   0.0909 .
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## (Dispersion parameter for binomial family taken to be 1)
## 
##     Null deviance: 87.720  on 63  degrees of freedom
## Residual deviance: 14.194  on 60  degrees of freedom
## AIC: 22.194
## 
## Number of Fisher Scoring iterations: 9</code></pre>
<div class="sourceCode" id="cb169"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb169-1"><a href="regression-models.html#cb169-1" tabindex="-1"></a>(ll.mod3 <span class="ot">&lt;-</span> <span class="fu">logLik</span>(gold.mod3))</span></code></pre></div>
<pre><code>## &#39;log Lik.&#39; -7.097155 (df=4)</code></pre>
<div class="sourceCode" id="cb171"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb171-1"><a href="regression-models.html#cb171-1" tabindex="-1"></a><span class="fu">anova</span>(gold.mod0, gold.mod3, <span class="at">test=</span><span class="st">&quot;LRT&quot;</span>)</span></code></pre></div>
<pre><code>## Analysis of Deviance Table
## 
## Model 1: gold ~ 1
## Model 2: gold ~ arsenic + antimony + lineament
##   Resid. Df Resid. Dev Df Deviance  Pr(&gt;Chi)    
## 1        63     87.720                          
## 2        60     14.194  3   73.526 7.499e-16 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
<div class="sourceCode" id="cb173"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb173-1"><a href="regression-models.html#cb173-1" tabindex="-1"></a><span class="fu">anova</span>(gold.mod1, gold.mod3, <span class="at">test=</span><span class="st">&quot;LRT&quot;</span>)</span></code></pre></div>
<pre><code>## Analysis of Deviance Table
## 
## Model 1: gold ~ arsenic
## Model 2: gold ~ arsenic + antimony + lineament
##   Resid. Df Resid. Dev Df Deviance Pr(&gt;Chi)  
## 1        62     22.603                       
## 2        60     14.194  2   8.4085  0.01493 *
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
<p><span class="math display">\[ \nabla  \]</span></p>

<div id="refs" class="references csl-bib-body hanging-indent" entry-spacing="0">
<div class="csl-entry">
Agresti, A., and B. Coull. 1998. <span>“Approximate Is Better Than <span>‘Exact’</span> for Interval Estimation of Binomial Proportions.”</span> <em>The American Statistician</em> 52 (2): 119–26.
</div>
<div class="csl-entry">
Agresti, Alan. 2002. <em>Categorical Data Analysis</em>. 2nd ed. New York: Wiley.
</div>
<div class="csl-entry">
Ali, E., W. Guang, and A. Ibrahim. 2014. <span>“Empirical Relations Between Compressive Strength and Microfabric Properties of Amphibolites Using Multivariate Regression, Fuzzy Inference, and Neural Networks: A Comparative Study.”</span> <em>Engineering Geology</em> 183: 230–40.
</div>
<div class="csl-entry">
Barnum, D. T., and J. M. Gleason. 1964. <span>“The Credibility of Drug Tests: A Multi-Stage Bayesian Analysis.”</span> <em>Industrial and Labor Relations Review</em> 47 (4): 610–21.
</div>
<div class="csl-entry">
Ben Ticha, M., W. Haddar, N. Meksi, A. Guesmi, and M. F. Mhenni. 2016. <span>“Improving Dyeability of Modified Cotton Fabrics by the Natural Aqueous Extract from Red Cabbage Using Ultrasonic Energy.”</span> <em>Carbohydrate Polymers</em> 154: 287–95.
</div>
<div class="csl-entry">
Bhatnagar, A., and V. K. Mehta. 2007. <span>“Efficacy of Deltamethrin and Cyfluthrin Impregnated Cloth over Uniform Against Mosquito Bites.”</span> <em>Medical Journal Armed Forces India</em> 63: 120–22.
</div>
<div class="csl-entry">
Chambers, G. F. 1889. <em>A Handbook of Descriptive and Practical Astronomy</em>. 4th ed. Oxford: Clarendon House.
</div>
<div class="csl-entry">
Clarke, R. D. 1946. <span>“An Application of the Poisson Distribution.”</span> <em>Journal of the Institute of Actuaries</em> 72: 481.
</div>
<div class="csl-entry">
Cohen, A. M. 1996. <span>“The Hands of Blues Guitarists.”</span> <em>American Music</em> 14 (4): 455–79.
</div>
<div class="csl-entry">
Csapo, J., Z. Csapo-Kiss, T. G. Martin, S. Folestad, O. Orwar, A. Tivesten, and S. Nemethy. 1995. <span>“Age Estimation of Old Carpets Based on Cystine and Cysteic Acid Content.”</span> <em>Analytica Chimica Acta</em> 300: 313–20.
</div>
<div class="csl-entry">
Dalal, S. R., E. B. Fowlkes, and B. Hoadley. 1989. <span>“Risk Analysis of the Space Shuttle: Pre-Challenger Prediction of Failure.”</span> <em>Journal of the American Statistical Association</em> 84 (408): 945–57.
</div>
<div class="csl-entry">
Dickey, D. A., and J. T. Arnold. 1995. <span>“Teaching Statistics with Data of Historic Significance: Galileo’s Gravity and Motion Experiments.”</span> <em>Journal of Statistics Education</em> 3 (1): 1–8.
</div>
<div class="csl-entry">
Durante, C., C. Baschieri, L. Bertacchini, D. Bertelli, M. Cocchi, A. Marchetti, D. Manzini, G. Papotti, and S. Sighinolfi. 2015. <span>“An Analytical Approach to Sr Isotope Ratio Detemination in Lambrusco Wines for Geographic Traceability Purposes.”</span> <em>Food Chemistry</em> 173: 557–63.
</div>
<div class="csl-entry">
Feller, William. 1968. <em>An Introduction to Probability Theory and Its Applications, Vol.1</em>. 3rd ed. New York: Wiley.
</div>
<div class="csl-entry">
Galton, F. 1886. <span>“Regression Towards Mediocrity in Hereditary Stature.”</span> <em>The Journal of the Anthropological Institute of Great Britain and Ireland</em> 15: 246–63.
</div>
<div class="csl-entry">
Halley, E. 1694. <span>“An Account of the Evaporation of Water, as It Was Experimented in Gresham Colledge in the Year 1693. With Some Observations Thereon.”</span> <em>Philosophical Transactions</em> 18: 183–90.
</div>
<div class="csl-entry">
Hanley, J. A. 2004. <span>“Transmuting Women into Men: Galton’s Family Data on Human Stature.”</span> <em>The American Statistician</em> 58 (3): 237–43.
</div>
<div class="csl-entry">
Kahneman, Daniel, Paul Slovic, and Amos Tversky. 1982. <em>Judgment Under Uncertainty: Heuristics and Biases</em>. 1st ed. Cambridge: Cambridge University Press.
</div>
<div class="csl-entry">
Kahneman, D., and A. Tversky. 1984. <span>“Choices, Values, and Frames.”</span> <em>American Psychologist</em> 35 (4): 341–50.
</div>
<div class="csl-entry">
Liang, D. G., J. R. Dusseldorp, C. van Schalkwyk, S. Hariswamy, S. Wood, V. Rose, and P. Moradi. 2016. <span>“Running Barbed Suture Quilting Reduces Abdominal Drainage in Perforator-Based Breast Reconstruction.”</span> <em>Journal of Plastic, Reconstructive &amp; Aesthetic Surgery</em> 69: 42–47.
</div>
<div class="csl-entry">
Lin, W., and J. Wang. 2016. <span>“An Integrated 3D Log Processing Optimization System for Hardwood Sawmills in Central Appalachia, USA.”</span> <em>Computers and Electronics in Agriculture</em> 82: 42–47.
</div>
<div class="csl-entry">
Masella, P., L. Guerrini, S. Spinelli, L. Calamai, P. Spugnoli, F. Illy, and A. Parenti. 2015. <span>“A New Espresso Brewing Method.”</span> <em>Journal of Food Engineering</em> 146: 204–8.
</div>
<div class="csl-entry">
Michelson, A. A., F. G. Pease, and F. Pearson. 1935. <span>“Measurement of the Velocity of Light in a Partial Vacuum.”</span> <em>Astrophysical Journal</em> 82: 26–61.
</div>
<div class="csl-entry">
Middleton, E. S., G. M. Smith, W. J. Cannon, and M. F. Ricks. 2014. <span>“Paleoindian Rock Art: Establishing the Antiquity of Great Basin Carved Abstract Petroglyphs in the Northern Great Basin.”</span> <em>Journal of Archaeological Science</em> 43: 21–30. <a href="https://doi.org/10.1016/j.jas.2013.12.006">https://doi.org/10.1016/j.jas.2013.12.006</a>.
</div>
<div class="csl-entry">
Page, L., D. A. Savage, and B. Torgler. 2014. <span>“Variation in Risk Seeking Behaviour Following Large Losses: A Natural Experiment.”</span> <em>European Economic Review</em> 71: 121–31.
</div>
<div class="csl-entry">
Peckmann, T. R., S. Scott, S. Meek, and P. Mahakkanukrauh. 2017. <span>“Sex Estimation from the Scapula in a Contemporary Thai Population: Applications for Forensic Anthropology.”</span> <em>Science and Justice</em> 57: 270–75.
</div>
<div class="csl-entry">
Poburka, P. J., R. R. Patel, and D. M. Bless. 2017. <span>“Voice-Vibratory Assessment with Laryngeal Imaging (VALI) Form: Reliability of Rating Stroboscopy and High-Speed Videoendoscopy.”</span> <em>Journal of Voice</em> 31 (4): 513.e1–14.
</div>
<div class="csl-entry">
Rusanganwa, J. 2013. <span>“Multimedia as a Means to Enhance Teaching Technical Vocabulary to Physics Undergraduates in Rwanda.”</span> <em>English for Specific Purposes</em> 32: 36–44.
</div>
<div class="csl-entry">
Sahoo, N. R., and H. S. Pandalai. 1999. <span>“Integration of Sparse Geologic Information in Gold Targeting Using Logistic Regression Analysis in the Hutti-Maski Schist Belt, Raichur, Karnataka, India - a Case Study.”</span> <em>Natural Resources Research</em> 8 (3): 233–50.
</div>
<div class="csl-entry">
Sanli, G. S., E. D. Kizilkanat, N. Boyan, E. T. Ozsahin, M. G. Bozkir, R. Soames, H. Erol, and O. Oguz. 2015. <span>“Stature Estimation Based on Hand Length and Foot Length.”</span> <em>Clinical Anatomy</em> 18 (8): 589–96.
</div>
<div class="csl-entry">
Sheldrake, R., P. Smart, and L. Avraamides. 2015. <span>“Automated Tests for Telephone Telepathy Using Mobile Phones.”</span> <em>Explore</em> 11 (4): 310–19.
</div>
<div class="csl-entry">
Short, J. 1763. <span>“Second Paper Concerning the Parallax of the Sun Determined from the Observations of the Late Transit of Venus, in Which This Subject Is Treated of More at Length, and the Quantity of the Parallax More Fully Ascertained.”</span> <em>Philosophical Transactions</em> 53: 300–345.
</div>
<div class="csl-entry">
Stigler, S. M. 1977. <span>“Do Robust Estimators Work with Real Data?”</span> <em>The Annals of Statistics</em> 5 (6): 1055–98.
</div>
<div class="csl-entry">
Thorndike, F. 1926. <span>“Applications of Poisson’s Probability Summation.”</span> <em>Bell System Technical Journal</em> 5: 604–24.
</div>
<div class="csl-entry">
Walter, S. R., W. T. M. Dunsmuir, and J. I. Westbrook. 2015. <span>“Studying Interruptions and Multitasking in Situ: The Untapped Potential of Quantitative Observational Studies.”</span> <em>International Journal of Human-Computer Studies</em> 79: 118–25.
</div>
<div class="csl-entry">
Winner, L. 2006. <span>“NASCAR Winston Cup Race Results for 1975-2003.”</span> <em>Journal of Statistics Education</em> 14 (3): 1–15.
</div>
<div class="csl-entry">
Xin, Y., S. Lu, N. Zhu, and W. Wu. 2012. <span>“Energy Consumption Quota of Four and Five Star Luxury Hotels Buildings in Hainan Province, China.”</span> <em>Energy and Buildings</em> 45: 250–56.
</div>
</div>
</div>
</div>
<h3>References</h3>
<div id="refs" class="references csl-bib-body hanging-indent" entry-spacing="0">
<div id="ref-csapo_1995" class="csl-entry">
Csapo, J., Z. Csapo-Kiss, T. G. Martin, S. Folestad, O. Orwar, A. Tivesten, and S. Nemethy. 1995. <span>“Age Estimation of Old Carpets Based on Cystine and Cysteic Acid Content.”</span> <em>Analytica Chimica Acta</em> 300: 313–20.
</div>
<div id="ref-dalal_1989" class="csl-entry">
Dalal, S. R., E. B. Fowlkes, and B. Hoadley. 1989. <span>“Risk Analysis of the Space Shuttle: Pre-Challenger Prediction of Failure.”</span> <em>Journal of the American Statistical Association</em> 84 (408): 945–57.
</div>
<div id="ref-sahoo_1999" class="csl-entry">
Sahoo, N. R., and H. S. Pandalai. 1999. <span>“Integration of Sparse Geologic Information in Gold Targeting Using Logistic Regression Analysis in the Hutti-Maski Schist Belt, Raichur, Karnataka, India - a Case Study.”</span> <em>Natural Resources Research</em> 8 (3): 233–50.
</div>
<div id="ref-sanli_2005" class="csl-entry">
Sanli, G. S., E. D. Kizilkanat, N. Boyan, E. T. Ozsahin, M. G. Bozkir, R. Soames, H. Erol, and O. Oguz. 2015. <span>“Stature Estimation Based on Hand Length and Foot Length.”</span> <em>Clinical Anatomy</em> 18 (8): 589–96.
</div>
<div id="ref-xin_2012" class="csl-entry">
Xin, Y., S. Lu, N. Zhu, and W. Wu. 2012. <span>“Energy Consumption Quota of Four and Five Star Luxury Hotels Buildings in Hainan Province, China.”</span> <em>Energy and Buildings</em> 45: 250–56.
</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="categorical-data-analysis.html" class="navigation navigation-prev navigation-unique" aria-label="Previous page"><i class="fa fa-angle-left"></i></a>

    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
  "sharing": {
    "github": false,
    "facebook": true,
    "twitter": true,
    "linkedin": false,
    "weibo": false,
    "instapaper": false,
    "vk": false,
    "whatsapp": false,
    "all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
  },
  "fontsettings": {
    "theme": "white",
    "family": "sans",
    "size": 2
  },
  "edit": {
    "link": null,
    "text": null
  },
  "history": {
    "link": null,
    "text": null
  },
  "view": {
    "link": null,
    "text": null
  },
  "download": null,
  "search": {
    "engine": "fuse",
    "options": null
  },
  "toc": {
    "collapse": "subsection",
    "link": "https://github.com/LarryWinner/STA2170-Notes1/edit/main/%s",
    "text": "Edit"
  }
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.9/latest.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
